		<!-- slider / carousel -->
		<div class="carousel slide" id="main-carousel" data-ride="carousel">

			<!-- slider content -->
			<div class="carousel-inner">
				<div class="item active">
					<div class="item-image">
						<img src="<?php echo $this->baseUrl('/image/'); ?>wheel-plus-balloons.jpg" alt="slider 1" height="600">
					</div>
					<div class="container">
						<div class="carousel-caption" style="text-align:center;">
							
							
							<h1 style="font-size:70px">Grow your business</h1>
							<h2>With effective digital and data analytics solutions</h2>
							
							
							<a href="#" class="btn btn-lg btn-primary" style="margin-top:20px;">Learn More</a>
						</div>
					</div>
				</div>				
			</div>
		</div>
		<!-- ./slider -->
		
		<!-- partners widget -->
		<div class="widget3 grey-background" style="background-color:#EEEEE;margin-bottom:0px;margin-top:0px; padding-bottom:50px; padding-top:50px;">
			<div class="container">
				<div class="row">
					<!-- partners slider -->
					<div class="col-md-12">
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- slider content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>tfl_logo.png" alt="tfl logo" width="170" height="50">
											</a>
										</div>
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
											</a>
										</div>
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>rbh.png" alt="Royal brompton NHS" width="170" height="50">
											</a>
										</div>
									</div>
								</div>
								<div class="item">
									<div class="row">
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>aacsl-logo.png" alt="AACSL" width="170" height="50">
											</a>
										</div>
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>intuitrics_logo.png" alt="Intuitrics" width="170" height="50">
											</a>
										</div>
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
											</a>
										</div>
									</div>
								</div>
							</div>
							<!-- ./slider content -->
						</div>
					</div>
					<!-- ./partners carousel -->
				</div>
			</div>
		</div>
		<!-- ./partners widget -->		

		<!-- widget container with grey background -->
		<div class="widget-container grey-background" style="background-color:#FFFFFF;">
			<div class="container">
				<!-- widget itself -->
				<div class="widget1">
					<div class="row">
						<div class="col-md-12 text-center">
							<h2>Take your business to the next level</h2>
							<p>From startups to big businesses, Vantworks can help your business succeed faster.</p>
							<hr style="border-bottom: 1px solid red; width:25%">
						</div>
					</div>
				</div>
				<!-- ./widget itself -->
			</div>
		</div>
		<!-- ./widget container with grey background -->

		<!-- widget with three options -->
		<div class="widget2 container">
			<div class="row">
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-mobile fa-fw"></i>
					</span>
					<h2 class="text-center">Web Applications</h2>
					<p>Vantworks has experience in building profesional and responsive web applications.</p>
					<p><a class="btn btn-sm btn-learn" href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#webApplications">Learn more</a></p>
				</div>
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-cloud fa-fw"></i>
					</span>
					<h2 class="text-center">Digital Marketing</h2>
					<p>Need to launch and scale your applications without limit on the cloud? Vantworks can help.</p>
					<p><a class="btn btn-sm btn-learn" href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#cloudHosting">Learn more</a></p>
				</div>
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-bar-chart fa-fw"></i>
					</span>
					<h2 class="text-center">Business Analytics</h2>
					<p>Generate business insights from enterprise data in order to gain a competitive edge filler here.</p>
					<p><a class="btn btn-sm btn-learn" href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#businessAnalytics">Learn more</a></p>
				</div>				
			</div>
		</div>
		
		
		<div class="grey-background wood-tile">
		
			<div class="container">
				<div class="why-use">
					 <div class="row">
						<div class="col-sm-6">
							<h2 style="color:#FFFFFF; font-size:45px;">Websites That Work</h2>
							<p style="padding-right: 60px; color:#FFFFFF; font-size:20px;">Your website is your online image. You deserve a good one. We build professional websites to lift your brand image and also drive business result engage and drive more customers to your business. You care about your business growth, so do we. Using best in class digital design and marketing solutions we help customers reach greater heights.</p>
							<!-- <p>AACSL team of trained professional accountants will help you handle your business accounting needs while you focus on your business growth.</p> -->
						</div>
						<div class="col-sm-6">
							<img class="why-use-image img-responsive" src="<?php echo $this->baseUrl('/image/home/'); ?>paper_work.png" width="250px" height="250px">
						</div>
					 </div><!-- /.row -->
				</div><!-- ./why-use -->
			</div><!-- /.container -->
		</div>			
			<div class="container">
				<div class="why-use">
					 <div class="row">
						<div class="col-sm-6 col-sm-push-6">
							<h2 style="font-size:40px; color:#333333;">Perform Higher</h2>
							<h2 style="font-size:40px; color:#333333;">Reach New Customers</h2>
							<p style="font-size:20px;">We are passionate about helping our customers achieve more by generating insights from business anlytics and data insights. Wouldn't you rather work with us.</p>
						</div>
						<div class="col-sm-6 col-sm-pull-6" style="padding-left:0px;">
							<img class="why-use-image img-responsive" src="<?php echo $this->baseUrl('/image/home/'); ?>regulatory_compliance.png" width="250px" height="250px">
						</div>
					 </div><!-- /.row - trusted community -->
				</div><!-- ./why-use -->
			</div><!-- /.container -->
		<div class="grey-background" style="background-color:#EE3824;">			
			<div class="container">
				<div class="why-use">			
					 <div class="row">
						<div class="col-sm-6">
							<h2 style="font-size:40px; color:#ffffff;">Partnership that Works</h2>
							<p style="padding-right:60px;font-size:20px; color:#ffffff;">Get a clearer understanding of your business cash flow, financial statement and profit & loss statement so you know where to make the right improvements.</p>
						</div>
						<div class="col-sm-6">
							<img class="why-use-image img-responsive" src="<?php echo $this->baseUrl('/image/home/'); ?>trans_statement.png" width="250px" height="250px">
						</div>
					 </div><!-- /.row -->
				</div><!-- ./why-use -->
			</div><!-- /.container -->	
		</div>
		
		<!-- ./widget with three options -->

		<!-- partners widget -->
		<div class="widget3 grey-background" style="background-color:#FFFFFF;margin-bottom:80px;margin-top:10px;">
			<div class="container">
				<div class="row">
					<div class="col-md-12" style="background-color:#FFFFFF; margin-bottom:30px;">
						<p class="client-works text-center" style="font-weight:bold;">Some clients works and projects</p>
						<p class="text-center" style="font-size:20px;font-weight:300;margin-top:10px;">We are happy to help startups to big corporations succeed.</p>
					</div>

					<!-- partners slider -->
					<div class="col-md-12">
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- slider content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>tfl_logo.png" alt="tfl logo" width="170" height="50">
											</a>
										</div>
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
											</a>
										</div>
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>rbh.png" alt="Royal brompton NHS" width="170" height="50">
											</a>
										</div>
									</div>
								</div>
								<div class="item">
									<div class="row">
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>aacsl-logo.png" alt="AACSL" width="170" height="50">
											</a>
										</div>
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>intuitrics_logo.png" alt="Intuitrics" width="170" height="50">
											</a>
										</div>
										<div class="col-xs-6 col-sm-4">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
											</a>
										</div>
									</div>
								</div>
							</div>
							<!-- ./slider content -->
						</div>
					</div>
					<!-- ./partners carousel -->
				</div>
			</div>
		</div>
		<!-- ./partners widget -->

		<!-- large 'why us' section -->
		<div class="widget4 widget-container why-background">
			<div class="container">
				<div class="row">
					<div class="col-md-4">
						<h3>Why Vantworks?</h3>
					</div>
					<div class="col-md-8">
						<h2>Agile</h2>
						<p>In today's idea economy, speed is key for a competitive edge. We work with you to bring your ideas to life fast through multiple iterations and feedback processes.</p>
						<h2>Professional</h2>
						<p>We follow professional and standard approaches in our delivery process, using best in class technologies and collaboration tools.</p>
						<h2>Affordable</h2>
						<p>Our services are built to world class standards and they are affordable for startups, entreprenuers and corporate organisations.</p>
						
						<a href="<?php echo $this->url(array('controller'=>'about','action'=>'why-vantworks'), 'default', true);?>">Learn more</a>
						
					</div>
				</div>
			</div>
		</div>
		<!-- ./large 'why us' section -->
		
		<div class="container" style="background-color:#FFFFFF; margin-top:50px;">
			<div class="why-use">
				 <div class="row">
					<div class="col-md-12 text-center">
						<h2>Ready to Grow? Talk to Us.</h2>
						<a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>" class="btn btn-primary" style="margin-top:10px;">Contact Us For a Quote</a>
					</div>
				 </div><!-- /.row - trusted community -->
			</div><!-- ./why-use -->
		</div><!-- /.container -->			