		<!-- slider / carousel -->
		<div class="carousel slide" id="main-carousel" data-ride="carousel">

			<!-- slider content -->
			<div class="carousel-inner">
				<div class="item active">
					<div class="item-image">
						<img src="<?php echo $this->baseUrl('/image/'); ?>london-eye-balloon4.jpg" alt="slider 1" height="600">
					</div>
					<div class="container">
						<div class="carousel-caption">
							
							
							<h1>Grow your business</h1>
							<h2>With effective digital design & data analytics solutions</h2>
							
							
							<a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>" class="btn btn-lg btn-primary" style="margin-top:20px;">Learn More</a>
						</div>
					</div>
				</div>				
			</div>
		</div>
		<!-- ./slider -->
		
		<!-- partners widget -->
		<div class="widget-clients">
			<div class="container">
				<div class="row">
					<!-- partners slider -->
					<div class="col-md-12">
					<h3 class="text-center">Trusted by clients of all sizes</h3>
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- slider content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-xs-6 col-sm-3">
												<img src="<?php echo $this->baseUrl('/image/'); ?>tfl_logo.png" alt="tfl logo" width="170" height="50">
										</div>
										<div class="col-xs-6 col-sm-3">
												<img src="<?php echo $this->baseUrl('/image/'); ?>rbh.png" alt="Royal brompton NHS" width="170" height="50">
										</div>	
										<div class="col-xs-6 col-sm-3">
												<img src="<?php echo $this->baseUrl('/image/'); ?>aacsl-logo.png" alt="AACSL" width="170" height="50">
										</div>										
										<div class="col-xs-6 col-sm-3">
												<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
										</div>
									</div>
								</div>

							</div>
							<!-- ./slider content -->
						</div>
					</div>
					<!-- ./partners carousel -->
				</div>
			</div>
		</div>
		<!-- ./partners widget -->		

		<!-- widget container with grey background -->
		<div class="widget-container">
			<div class="container">
				<!-- widget itself -->
				<div class="widget1">
					<div class="row">
						<div class="col-md-12 text-center">
							<h2>Take your business to the next level</h2>
							<p>From startup to enterprise, Vantworks can help your business succeed better.</p>
							<hr>
						</div>
					</div>
				</div>
				<!-- ./widget itself -->
			</div>
		</div>
		<!-- ./widget container with grey background -->

		<!-- widget with three options -->
		<div class="widget2 container">
			<div class="row">
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-mobile fa-fw"></i>
					</span>
					<h2>Digital Design</h2>
					<p>We build engaging and functional responsive digital experiences that elevates your brand's online image.</p>
					<p><a class="btn btn-sm btn-learn" href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#webApplications">Learn more</a></p>
				</div>
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-bar-chart fa-fw"></i>
					</span>
					<h2>Business Intelligence</h2>
					<p>Generate actionable insights from your business data to gain competitive advantage and improve performance.</p>
					<p><a class="btn btn-sm btn-learn" href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#businessAnalytics">Learn more</a></p>
				</div>					
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-cloud fa-fw"></i>
					</span>
					<h2>Digital Marketing</h2>
					<p>Promote your products and services with effective campaigns that generate leads and improve website conversions.</p>
					<p><a class="btn btn-sm btn-learn" href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#cloudHosting">Learn more</a></p>
				</div>			
			</div>
		</div>
		
		
		<div class="grey-background wood-tile" style="background-attachment:fixed;">
		
			<div class="container benefits-box">
				<div class="benefits">
					 <div class="row">
						<div class="col-sm-7" style="padding-top:60px;">
							<h2>Websites That Work</h2>
							<p>More than just online presence, we build web applications that impact your business bottom line using design and technology. Whether you need to engage more prospects or increase sales, Vantworks is happy to help.</p>
						</div>
						<div class="col-sm-5">
							<img class="benefits-image img-responsive" src="<?php echo $this->baseUrl('/image/home/'); ?>ridebliss-screenshot.png" width="250px" height="250px">
						</div>
					 </div><!-- /.row -->
				</div><!-- ./benefits -->
			</div><!-- /.container -->
		</div>			
			<div class="container benefits-box">
				<div class="benefits benefits-alt">
					 <div class="row">
						<div class="col-sm-7 col-sm-push-5" style="padding-top:60px;">
							<h2>Reach New Audiences</h2>
							<p>Your website is your business digital marketing medium. We build online marketing strategies around your website to attract new customers, delight existing ones and improve revenue.</p>
						</div>
						<div class="col-sm-5 col-sm-pull-7">
							<img class="img-responsive" src="<?php echo $this->baseUrl('/image/home/'); ?>regulatory_compliance.png" width="250px" height="250px">
						</div>
					 </div><!-- /.row - trusted community -->
				</div><!-- ./benefits -->
			</div><!-- /.container -->
		<div class="brand-red benefits-box">			
			<div class="container">
				<div class="benefits">			
					 <div class="row">
						<div class="col-sm-7" style="padding-top:60px;">
							<h2>Partnerships That Work</h2>
							<p>We partner with our clients to achieve set business goals by using engaging digital design and data-driven marketing solutions that deliver results. We take care of your digital needs while you focus on your business. That's a winning combination.</p>
						</div>
						<div class="col-sm-5">
							<img class="benefits-image img-responsive" src="<?php echo $this->baseUrl('/image/home/'); ?>trans_statement.png" width="250px" height="250px">
						</div>
					 </div><!-- /.row -->
				</div><!-- ./benefits -->
			</div><!-- /.container -->	
		</div>
		
		<!-- ./widget with three options -->

		<!-- testimonial widget -->
		<div class="widget3 reviews-set">
			<div class="container">
				<div class="row">
					<!-- testimonial slider -->
					<div class="col-md-12">
					<h3>What Our Customers Say</h3>
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- testimonial content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-md-8 col-md-offset-2 text-center">
											<p><em>"We successfully launched our new website that clearly highlights our value propositions. Our clients love it. Thanks to Vantworks."</em>
											</p>
											<p><strong>Rasheed S., Director, AASCL Accountants</strong></p>
										</div>
									</div>								
								</div>
								<div class="item">
									<div class="row">
										<div class="col-md-8 col-md-offset-2 text-center">
											<p><em>"Vantworks always deliver quality web hosting service for my business. I have come to rely on them as my technology partner for growth."</em>
											</p>
											<p><strong>Tunde O., Director, Intuitrics</strong></p>
										</div>
									</div>				
								</div>
							</div>
							<!-- ./slider content -->
						</div>
					</div>
					<!-- ./testimonial carousel -->
				</div>
			</div>
		</div>
		<!-- testimonial widget-->	

		<!-- large 'why us' section -->
		<div class="widget4 widget-container why-background" style="background-attachment:fixed;">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<h3>Why <br>Vantworks?</h3>
					</div>
					<div class="col-md-9">	
						<div class="row">
							<div class="col-md-1 col-sm-1 col-xs-1">
							<img src="<?php echo $this->baseUrl('/image/home/'); ?>checkmark.png" width="30" height="30">
							</div>
							<div class="col-md-11 col-sm-11 col-xs-11" >
								<h2>Agile</h2>
								<p>In today's idea economy, speed is key for a competitive edge. We work with you to bring your ideas to life fast through multiple iterations and feedback processes.
								</p>
							</div>
						</div>		
						<div class="row">
							<div class="col-md-1 col-sm-1 col-xs-1">
							<img src="<?php echo $this->baseUrl('/image/home/'); ?>checkmark.png" width="30" height="30">
							</div>
							<div class="col-md-11 col-sm-11 col-xs-11">
								<h2>Professional</h2>
								<p>We follow professional and standard approaches in our delivery process, using best in class technologies and collaboration tools.
								</p>
							</div>
						</div>	
						<div class="row">
							<div class="col-md-1 col-sm-1 col-xs-1">
							<img src="<?php echo $this->baseUrl('/image/home/'); ?>checkmark.png" width="30" height="30">
							</div>
							<div class="col-md-11 col-sm-11 col-xs-11">
								<h2>Affordable</h2>
								<p>Our services are built to world class standards and they are affordable for startups, entreprenuers and corporate organisations.
								</p>
							</div>
						</div>						
					
						<a href="<?php echo $this->url(array('controller'=>'about','action'=>'why-vantworks'), 'default', true);?>">Learn more</a>
						
					</div>
				</div>
			</div>
		</div>
		<!-- ./large 'why us' section -->
		<div class="widget-action-hm">
			<div class="container">
				<div class="why-use">
					 <div class="row">
						<div class="col-md-12 text-center">
							<h2 style="font-size:36px;">Ready to Grow?</h2>
							<a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>" class="btn btn-primary">Contact Us For a Quote</a>
						</div>
					 </div><!-- /.row - trusted community -->
				</div><!-- ./why-use -->
			</div><!-- /.container -->	
		</div>	