		<!-- slider / carousel -->
		<div class="carousel slide" id="main-carousel" data-ride="carousel">

			<!-- slider content -->
			<div class="carousel-inner">
				<div class="item active">
					<div class="item-image">
						<img src="<?php echo $this->baseUrl('/image/'); ?>london-eye-balloon4.jpg" alt="slider 1" height="600">
					</div>
					<div class="container">
						<div class="carousel-caption">
							
							
							<h1>Grow your business</h1>
							<h2>With effective digital design & data analytics solutions</h2>
							
							
							<a href="#" class="btn btn-lg btn-primary" style="margin-top:20px;">Learn More</a>
						</div>
					</div>
				</div>				
			</div>
		</div>
		<!-- ./slider -->
		
		<!-- partners widget -->
		<div class="widget-clients">
			<div class="container">
				<div class="row">
					<!-- partners slider -->
					<div class="col-md-12">
					<h3 class="text-center">Trusted by clients of all sizes</h3>
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- slider content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-xs-6 col-sm-3">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>tfl_logo.png" alt="tfl logo" width="170" height="50">
											</a>
										</div>
										<div class="col-xs-6 col-sm-3">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>rbh.png" alt="Royal brompton NHS" width="170" height="50">
											</a>
										</div>	
										<div class="col-xs-6 col-sm-3">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>aacsl-logo.png" alt="AACSL" width="170" height="50">
											</a>
										</div>										
										<div class="col-xs-6 col-sm-3">
											<a href="#" target="_blank">
												<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
											</a>
										</div>
									</div>
								</div>

							</div>
							<!-- ./slider content -->
						</div>
					</div>
					<!-- ./partners carousel -->
				</div>
			</div>
		</div>
		<!-- ./partners widget -->		

		<!-- widget container with grey background -->
		<div class="widget-container">
			<div class="container">
				<!-- widget itself -->
				<div class="widget1">
					<div class="row">
						<div class="col-md-12 text-center">
							<h2>Take your business to the next level</h2>
							<p>From startup to enterprise, Vantworks can help your business succeed faster.</p>
							<hr>
						</div>
					</div>
				</div>
				<!-- ./widget itself -->
			</div>
		</div>
		<!-- ./widget container with grey background -->

		<!-- widget with three options -->
		<div class="widget2 container">
			<div class="row">
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-mobile fa-fw"></i>
					</span>
					<h2>Digital Design</h2>
					<p>Vantworks has experience in building profesional and responsive web applications.</p>
					<p><a class="btn btn-sm btn-learn" href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#webApplications">Learn more</a></p>
				</div>
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-cloud fa-fw"></i>
					</span>
					<h2>Digital Marketing</h2>
					<p>Need to launch and scale your applications without limit on the cloud? Vantworks can help.</p>
					<p><a class="btn btn-sm btn-learn" href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#cloudHosting">Learn more</a></p>
				</div>
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-bar-chart fa-fw"></i>
					</span>
					<h2>Business Analytics</h2>
					<p>Generate business insights from enterprise data in order to gain a competitive edge filler here.</p>
					<p><a class="btn btn-sm btn-learn" href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#businessAnalytics">Learn more</a></p>
				</div>				
			</div>
		</div>
		
		
		<div class="grey-background wood-tile" style="background-attachment:fixed;">
		
			<div class="container benefits-box">
				<div class="benefits">
					 <div class="row">
						<div class="col-sm-6">
							<h2>Websites That Work</h2>
							<p>Your website is your online image. You deserve a good one. We build professional websites that elevates your brand image and also drive business result engage and drive more customers to your business.</p>
						</div>
						<div class="col-sm-6">
							<img class="benefits-image img-responsive" src="<?php echo $this->baseUrl('/image/home/'); ?>ridebliss-screenshot.png" width="250px" height="250px">
						</div>
					 </div><!-- /.row -->
				</div><!-- ./benefits -->
			</div><!-- /.container -->
		</div>			
			<div class="container benefits-box">
				<div class="benefits benefits-alt">
					 <div class="row">
						<div class="col-sm-6 col-sm-push-6">
							<h2>Reach New Audience</h2>
							<p>We are passionate about helping our customers achieve more by generating insights from business anlytics and data insights. Wouldn't you rather work with us.</p>
						</div>
						<div class="col-sm-6 col-sm-pull-6">
							<img class="img-responsive" src="<?php echo $this->baseUrl('/image/home/'); ?>regulatory_compliance.png" width="250px" height="250px">
						</div>
					 </div><!-- /.row - trusted community -->
				</div><!-- ./benefits -->
			</div><!-- /.container -->
		<div class="brand-red benefits-box">			
			<div class="container">
				<div class="benefits">			
					 <div class="row">
						<div class="col-sm-6">
							<h2>Partnership that Works</h2>
							<p>Get a clearer understanding of your business cash flow, financial statement and profit & loss statement so you know where to make the right improvements.</p>
						</div>
						<div class="col-sm-6">
							<img class="benefits-image img-responsive" src="<?php echo $this->baseUrl('/image/home/'); ?>trans_statement.png" width="250px" height="250px">
						</div>
					 </div><!-- /.row -->
				</div><!-- ./benefits -->
			</div><!-- /.container -->	
		</div>
		
		<!-- ./widget with three options -->

		<!-- testimonial widget -->
		<div class="widget3 reviews-set">
			<div class="container">
				<div class="row">
					<!-- testimonial slider -->
					<div class="col-md-12">
					<h3>What Our Customers Say</h3>
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- testimonial content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-md-3 text-center">
												<img src="<?php echo $this->baseUrl('/image/home/'); ?>pic-testimonial.png" width="140" height="140">
										</div>
										<div class="col-md-7 offset-md-2">
											<p>"We successfully launch our new website that clearly highlights our value propositions. Our clients love it. Thanks to Vantworks"
											</p>
											<p>Chuks O, Director, Intuitrics</p>
										</div>
									</div>								
								</div>
								<div class="item">
									<div class="row">
										<div class="col-md-3 text-center">
												<img src="<?php echo $this->baseUrl('/image/home/'); ?>pic-testimonial.png" width="140" height="140">
										</div>
										<div class="col-md-7 offset-md-2">
											<p>"Thanks to Vantworks, we turned what could have been a million-dollar mistake into a major win both for us and our users."
											</p>
											<p>Tunde O, Director, Intuitrics</p>
										</div>
									</div>				
								</div>
							</div>
							<!-- ./slider content -->
						</div>
					</div>
					<!-- ./testimonial carousel -->
				</div>
			</div>
		</div>
		<!-- testimonial widget-->	

		<!-- large 'why us' section -->
		<div class="widget4 widget-container why-background" style="background-attachment:fixed;">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<h3>Why <br>Vantworks?</h3>
					</div>
					<div class="col-md-9">	
						<div class="row">
							<div class="col-md-1 col-sm-1 col-xs-1">
							<img src="<?php echo $this->baseUrl('/image/home/'); ?>checkmark.png" width="30" height="30">
							</div>
							<div class="col-md-11 col-sm-11 col-xs-11" >
								<h2>Agile</h2>
								<p>In today's idea economy, speed is key for a competitive edge. We work with you to bring your ideas to life fast through multiple iterations and feedback processes.
								</p>
							</div>
						</div>		
						<div class="row">
							<div class="col-md-1 col-sm-1 col-xs-1">
							<img src="<?php echo $this->baseUrl('/image/home/'); ?>checkmark.png" width="30" height="30">
							</div>
							<div class="col-md-11 col-sm-11 col-xs-11">
								<h2>Professional</h2>
								<p>We follow professional and standard approaches in our delivery process, using best in class technologies and collaboration tools.
								</p>
							</div>
						</div>	
						<div class="row">
							<div class="col-md-1 col-sm-1 col-xs-1">
							<img src="<?php echo $this->baseUrl('/image/home/'); ?>checkmark.png" width="30" height="30">
							</div>
							<div class="col-md-11 col-sm-11 col-xs-11">
								<h2>Affordable</h2>
								<p>Our services are built to world class standards and they are affordable for startups, entreprenuers and corporate organisations.
								</p>
							</div>
						</div>						
					
						<a href="<?php echo $this->url(array('controller'=>'about','action'=>'why-vantworks'), 'default', true);?>">Learn more</a>
						
					</div>
				</div>
			</div>
		</div>
		<!-- ./large 'why us' section -->
		<div class="widget-action-hm">
			<div class="container">
				<div class="why-use">
					 <div class="row">
						<div class="col-md-12 text-center">
							<h2>Ready to Grow? Talk to Us.</h2>
							<a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>" class="btn btn-primary">Contact Us For a Quote</a>
						</div>
					 </div><!-- /.row - trusted community -->
				</div><!-- ./why-use -->
			</div><!-- /.container -->	
		</div>	