<?php $this->headTitle('Business Analytics'); ?>


		<!-- main content header -->
		<div class="widget-container grey-background">
			<div class="main-title">
				<h1>Business Analytics</h1>
			</div>
		</div>
		<!-- ./main content header -->

		<!-- main top content -->
		<div class="container">
			<div class="widget6">
				<h1>We design and implement robust data warehouse and business intellegence solutions using Oracle and open-source technologies.</h1>
				<div class="row">
					<div class="col-md-5 col-sm-6">
						<img src="<?php echo $this->baseUrl('/image/'); ?>ad1.png" alt="ad" width="474" height="273">
					</div>
					<div class="col-md-7 col-sm-6">
						<h3>Business Insights</h3>
						<p class="text-italic">Using our expertise in data warehouse technology, we generate actionable insights from your massive enterprise data to enable your organisations stay competitive and achieve business strategies.</p>
					
					</div>
				</div>
			</div>
		</div>
		<!-- ./main top content -->

		<!-- highlights -->
		<div class="widget-container widget_band">
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="icon">
							<img src="<?php echo $this->baseUrl('/image/'); ?>icon1.png" alt="icon" width="60" height="68">
						</div>
						<h2>Data Warehouse</h2>
						<p>Whether it is open-source RDBMS or Oracle, your heterogenous business data can be modelled and integrated into a single repository.</p>
					</div>
					<div class="col-sm-4">
						<div class="icon">
							<img src="<?php echo $this->baseUrl('/image/'); ?>icon2.png" alt="icon" width="60" height="68">
						</div>
						<h2>Database Management</h2>
						<p>From open-source MySQL RDBMS to proprietary Oracle, we design and build robust database solution to store and protect your data.</p>
					</div>
					<div class="col-sm-4">
						<div class="icon">
							<img src="<?php echo $this->baseUrl('/image/'); ?>icon3.png" alt="icon" width="60" height="41">
						</div>
						<h2>Business Intelligence</h2>
						<p>Gain quick insights across your business and measure KPIs trend with interactive reports and dashboards developed to meet your needs .</p>
					</div>
				</div>
			</div>
		</div>
		<!-- ./highlights -->

		<!-- features -->
		<div class="widget-container widget8">
			<div class="container">
				<h1>Business Analytics Solutions</h1>
				<div class="row feature-table">
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-database fa-fw"></i>
						<p>Database design</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-copy fa-fw"></i>
						<p>Backup and recovery</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-gears fa-fw"></i>
						<p>Performance tuning</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-users fa-fw"></i>
						<p>Data security</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-bolt fa-fw"></i>
						<p>Data integration</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-cubes fa-fw"></i>
						<p>Data modelling</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-bar-chart fa-fw"></i>
						<p>Reports and Dashboards</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-line-chart fa-fw"></i>
						<p>Business Intellegence</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-rocket fa-fw"></i>
						<p>Actionable insights</p>
					</div>					
				</div>
			</div>
		</div>
		<!-- ./features -->

		<!-- take action -->
		<div class="container">
			<div class="widget-container widget9 grey-background">
				<div class="row">
					<div class="col-md-4 col-sm-12 btn-container">
						<a href="#" class="btn btn-primary">Contact Us For a Quote</a>
					</div>
					<div class="col-md-8 col-sm-12">
						<p>Email or call us: <a href="mailto:sales@website.com">hello@vantworks.co.uk</a> | <a href="tel:180012345678">+1 (800) 123-4567</a></p>
					</div>
				</div>
			</div>
		</div>
		<!-- ./take action -->