<?php $this->headTitle('Vantworks | Digital Marketing'); ?>

		<div class="widget-header-banner widget-pg-dm">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Digital Marketing</h1>
						<h2>Drive your business growth with the power of digital.</h2>
					</div>
				</div>
			</div>
		</div>	
			
		
		
		
		</div>
		<!-- main content header -->
		<div class="title-container grey-background">
			<div class="main-title">
				<h2>Drive your business growth with the power of digital.</h2>
			</div>
		</div>
		<!-- ./main content header -->

		<!-- main top content -->
		<div class="container">
			<div class="widget6">
				<h1></h1>
				<div class="row">
					<div class="col-md-5 col-sm-6">
						<img src="<?php echo $this->baseUrl('/image/'); ?>app-laptop-screen.png" alt="ad" width="474" height="273">
					</div>
					<div class="col-md-7 col-sm-6">
						<h3>Drive Growth. Perform Higher</h3>
						<p class="text-italic">Your business has potentials for sustainable growth. Through the power of effective digital marketing we can help you achieve just that. We work with you to understand your needs and then design a winning strategy to reach more customers. </p>
					
					</div>
				</div>
			</div>
		</div>
		<!-- ./main top content -->

		<!-- highlights -->
		<div class="widget-container widget_band">
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="icon">
							<i class="fa fa-rocket fa-fw"></i>
						</div>
						<h2>Makerting Campaigns</h2>
						<p>Vantworks partner with you to plan and execute campaigns to attract potential customers, delight existing customers and achieve success.</p>
					</div>
					<div class="col-sm-4">
						<div class="icon">
							<i class="fa fa-gears fa-fw"></i>
						</div>
						<h2>Digital Experience</h2>
						<p>A good website is your business primary digital estate. We build mobile and desktop websites with engaing user experience that drives sales.</p>
					</div>
					<div class="col-sm-4">
						<div class="icon">
							<i class="fa fa-balance-scale fa-fw"></i>
						</div>
						<h2>Data-driven Analysis</h2>
						<p>Our data analytics approach enables us analyse your marketing activities to make optimisation for better outcomes - conversions and lead generation.</p>
					</div>
				</div>
			</div>
		</div>
		<!-- ./highlights -->

		<!-- features -->
		<div class="widget-container widget8">
			<div class="container">
				<h1>Digital Marketing Solutions</h1>
				<div class="row feature-table">
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-check-square fa-fw"></i>
						<p>Email marketing</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-check-square fa-fw"></i>
						<p>Search engine marketing</p>
					</div>					
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-check-square fa-fw"></i>
						<p>Social media marketing</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-check-square fa-fw"></i>
						<p>Content marketing</p>
					</div>					
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-check-square fa-fw"></i>
						<p>Viral Marketing</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-check-square fa-fw"></i>
						<p>Paid Search (PPC)</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-check-square fa-fw"></i>
						<p>Cloud launch</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-check-square fa-fw"></i>
						<p>Search engine optimisation</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-check-square fa-fw"></i>
						<p>Growth strategy</p>
					</div>
				</div>
			</div>
		</div>
		<!-- ./features -->

		<!-- take action -->
		<div class="widget-action">
			<div class="container">
				<div class="widget-container take-action">
					<div class="row">
						<div class="col-md-12 text-center">
							<p>Ready to Improve Your Marketing?</p>
							<a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>" class="btn btn-primary">Contact Us Today</a>
						</div>
					</div>
				</div>
			</div>
		</div>	
		<!-- ./take action -->