<?php $this->headTitle('Vantworks Solutions | Web Applications, Cloud Hosting, Business Analytics'); ?>

	
<!-- main content header -->
		<!-- slider / carousel -->
		<div class="carousel slide" id="main-carousel" data-ride="carousel">
			<!-- indicators - circles on the bottom -->


			<!-- slider content -->
			<div class="carousel-inner">
				<div class="item active">
					<div class="item-image">
						<img src="<?php echo $this->baseUrl('/image/'); ?>lady_phone_mini.jpg" alt="slider 1">
					</div>
					<div class="container">
						<div class="carousel-caption">
							<h1>Vantworks Solutions</h1>
							<h2>Partnership that works.</h2>
							<p>We work with you to deliver services that works.</p>
						</div>
					</div>
				</div>
			</div>
			<!-- ./slider content -->
		<div class="title-container grey-background">
			<div class="main-title">
				<h1>Vantworks Solutions</h1>
			</div>
		</div>			

		</div>
		<!-- ./main content header -->

		<!-- main content -->
		<div class="container soln-container">
			<div class="row">
				<div class="col-sm-12 col-xs-12 soln-header">
					<h2>Web Development</h2><span id="webApplications"></span>
				</div>
				<div class="col-sm-6 col-sm-push-6 ">
					<img class="img-responsive pull-right" src="<?php echo $this->baseUrl('/image/'); ?>app-laptop-screen.png" width="380" height="218">
				</div>					
				<div class="col-sm-6 col-xs-12 col-md-6 col-sm-pull-6">
						
							<p>
							From idea conceptualization to launching on the cloud, Vantworks can help build your dream project fast. We use best-in-class web frameworks and platforms to design and host your web apps. We work with both startups and corporate organisations.
							</p>
						
						<p><a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'web-applications'), 'default', true);?>" class="btn btn-primary">Learn More</a>
						</p>
				</div>			
			</div>
			<div class="separator"></div>
		</div>	
		<div class="container soln-container-next">		
			<div class="row">
				<div class="col-md-6 col-md-offset-6 col-xs-12 soln-header">
					<h2>Digital Marketing</h2><span id="cloudHosting"></span>
				</div>	
				<div class="col-sm-6 col-md-6">
					<img class="img-responsive" src="<?php echo $this->baseUrl('/image/'); ?>lady_phone_mini.png" width="380" height="218">
				</div>				
				<div class="col-sm-6 col-xs-12 col-md-6">
						
							<p>We choose the best cloud hosting platform to launch your project so you can scale without limit as your web app gets popular. Server resources are made available to your application on-demand. We provide on-going cloud support for your projects, so you can focus on your actual business growth.
							</p>
						
						<p><a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'web-applications'), 'default', true);?>" class="btn btn-primary">Learn More</a>
						</p>
				</div>
			</div>
			<div class="separator"></div>
		</div>
		<div class="container soln-container-next">
			<div class="row">
				<div class="col-sm-12 col-xs-12 soln-header">
					<h2>Business Analytics</h2> <span id="businessAnalytics"></span>
				</div>	
				<div class="col-sm-6 col-sm-push-6">
					<img class="img-responsive pull-right" src="<?php echo $this->baseUrl('/image/'); ?>bi-dashboard.png" width="380" height="218">
				</div>					
				<div class="col-sm-6 col-xs-12 col-sm-pull-6">
						
							<p>
							Vantworks has the expertise of generating business insights from your enterprise data. With years of experience designing and supporting terabytes of data for large corporations, you can count on us in delivering robust business intelligence solutions for your organisation.
							</p>
						
						<p><a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'business-analytics'), 'default', true);?>" class="btn btn-primary">Learn More</a>
						</p>
				</div>			
			</div>
			<div class="separator"></div>
		</div>	
		
		<div class="container soln-container-next">		
			<div class="row">
				<div class="col-md-6 col-md-offset-6 col-xs-12 soln-header">
					<h2>Cloud Hosting</h2><span id="cloudHosting"></span>
				</div>	
				<div class="col-sm-6 col-md-6">
					<img class="img-responsive" src="<?php echo $this->baseUrl('/image/'); ?>lady_phone_mini.png" width="380" height="218">
				</div>				
				<div class="col-sm-6 col-xs-12 col-md-6">
						
							<p>We choose the best cloud hosting platform to launch your project so you can scale without limit as your web app gets popular. Server resources are made available to your application on-demand. We provide on-going cloud support for your projects, so you can focus on your actual business growth.
							</p>
						
						<p><a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'web-applications'), 'default', true);?>" class="btn btn-primary">Learn More</a>
						</p>
				</div>
			</div>
			<div class="soln_end"></div>
		</div>		
		
		<!-- take action -->
		<div class="container">
			<div class="widget-container widget9 grey-background">
				<div class="row">
					<div class="col-md-4 col-sm-12 btn-container">
						<a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>" class="btn btn-primary">Contact Us For a Quote</a>
					</div>
					<div class="col-md-8 col-sm-12">
						<p>Email or call us: <a href="mailto:hello@vantworks.co.uk">hello@vantworks.co.uk</a> | <a href="tel:+442030868255">0203 086 8255</a></p>
					</div>
				</div>
			</div>
		</div>
		<!-- ./take action -->		