<?php $this->headTitle('Vantworks | Web Applications, Cloud Hosting'); ?>


		<!-- main content header -->
		<div class="title-container grey-background">
			<div class="main-title">
				<h1>Web Applications</h1>
			</div>
		</div>
		<!-- ./main content header -->

		<!-- main top content -->
		<div class="container">
			<div class="widget6">
				<h1>We build professional and responsive web applications with the latest frameworks.</h1>
				<div class="row">
					<div class="col-md-5 col-sm-6">
						<img src="<?php echo $this->baseUrl('/image/'); ?>app-laptop-screen.png" alt="ad" width="474" height="273">
					</div>
					<div class="col-md-7 col-sm-6">
						<h3>Launch Your Idea</h3>
						<p class="text-italic">Vantworks team can help turn your tech ideas into tangible web apps your target audience will love. We work with you to understand and conceptualize your ideas and then build prototypes. Once you are happy, your app is launched in the cloud. </p>
					
					</div>
				</div>
			</div>
		</div>
		<!-- ./main top content -->

		<!-- highlights -->
		<div class="widget-container widget_band">
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="icon">
							<i class="fa fa-rocket fa-fw"></i>
						</div>
						<h2>Agile</h2>
						<p>We work with you to bring your ideas to life fast through multiple iterations, based on feedbacks and testing.</p>
					</div>
					<div class="col-sm-4">
						<div class="icon">
							<i class="fa fa-gears fa-fw"></i>
						</div>
						<h2>Latest Technology</h2>
						<p>Using the latest web development tools and frameworks, we build standard and responsive apps that adapts to any device.</p>
					</div>
					<div class="col-sm-4">
						<div class="icon">
							<i class="fa fa-balance-scale fa-fw"></i>
						</div>
						<h2>Affordable</h2>
						<p>Although our works are professionally done, individual client needs are tailored to fit their budget, scope and target market.</p>
					</div>
				</div>
			</div>
		</div>
		<!-- ./highlights -->

		<!-- features -->
		<div class="widget-container widget8">
			<div class="container">
				<h1>Web Application Solutions</h1>
				<div class="row feature-table">
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-lightbulb-o fa-fw"></i>
						<p>Idea Elicitation</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-paint-brush fa-fw"></i>
						<p>Design</p>
					</div>					
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-code fa-fw"></i>
						<p>Coding</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-gears fa-fw"></i>
						<p>Development</p>
					</div>					
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-tablet fa-fw"></i>
						<p>Prototyping</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-users fa-fw"></i>
						<p>Unit Testing</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-cloud-upload fa-fw"></i>
						<p>Cloud launch</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-search fa-fw"></i>
						<p>Search engine optimisation</p>
					</div>
					<div class="col-md-4 col-sm-6">
						<i class="fa fa-arrow-circle-up fa-fw"></i>
						<p>Growth strategy</p>
					</div>
				</div>
			</div>
		</div>
		<!-- ./features -->

		<!-- take action -->
		<div class="container">
			<div class="widget-container widget9 grey-background">
				<div class="row">
					<div class="col-md-4 col-sm-12 btn-container">
						<a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>" class="btn btn-primary">Contact Us For a Quote</a>
					</div>
					<div class="col-md-8 col-sm-12">
						<p>Email or call us: <a href="mailto:hello@vantworks.co.uk">hello@vantworks.co.uk</a> | <a href="tel:+442030868255">0203 086 8255</a></p>
					</div>
				</div>
			</div>
		</div>
		<!-- ./take action -->