<?php $this->headTitle('Vantworks Services'); ?>

	
<!-- main content header -->
		<div class="widget-container grey-background">
			<div class="main-title">
				<h1>Vantworks Solutions</h1>
			</div>
		</div>
		<!-- ./main content header -->

		<!-- main content -->

		<div class="container widget5-container">
			<div class="row">
				<!-- row 1, grid 1 -->
				<div class="col-md-4 col-xs-12">
					<div class="widget5">
						<div class="header-image">
							<img src="<?php echo $this->baseUrl('/image/'); ?>head-image1.png" alt="head-image" width="260" height="187">
						</div>
						<div class="widget-header">
							
							<h1>Web Application</h1>
						</div>
						<div class="widget-content">
							
							<p>With a 100% uptime SLA your ads are guaranteed to be served at all times.</p>
							<a href="#" class="btn btn-primary">Learn More</a>
						</div>
					</div>
				</div>
				<!-- row 2, grid 1 -->
				<div class="col-md-4 col-xs-12">
					<div class="widget5">
						<div class="header-image">
							<img src="<?php echo $this->baseUrl('/image/'); ?>head-image2.png" alt="head-image" width="260" height="187">
						</div>
						<div class="widget-header">
							
							<h1>Enterprise BI</h1>
						</div>
						<div class="widget-content">
						
							<p>Creative through digital demands speed. You've spent the time creating the ad, app, video or website. Now take the next step and deliver it right.</p>
							<a href="#" class="btn btn-primary">Learn More</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-xs-12">
					<div class="widget5">
						<div class="header-image">
							<img src="<?php echo $this->baseUrl('/image/'); ?>head-image3.png" alt="head-image" width="260" height="187">
						</div>
						<div class="widget-header">
							
							<h1>Cloud Hosting</h1>
						</div>
						<div class="widget-content">
							
							<p>MaxCDN provides powerful tools to get up and running quickly so that you can easily provide CDN to your clientele.</p>
							<a href="#" class="btn btn-primary">Learn More</a>
						</div>
					</div>
				</div>
				<!-- when needed, row 3, grid 1 -->
				<!-- when needed, row 4, grid 1 -->
			</div>
			<div class="row">
				<!-- row 1, grid 1 -->
				<div class="col-md-4 col-xs-12">
					<div class="widget5">
						<div class="header-image">
							<img src="<?php echo $this->baseUrl('/image/'); ?>head-image1.png" alt="head-image" width="260" height="187">
						</div>
						<div class="widget-header">
							<i class="fa fa-check fa-fw"></i>
							<h1>Publishers</h1>
						</div>
						<div class="widget-content">
							<i class="fa fa-info-circle fa-fw"></i>
							<p>With a 100% uptime SLA your ads are guaranteed to be served at all times.</p>
							<a href="#" class="btn btn-primary">Learn More</a>
						</div>
					</div>
				</div>
				<!-- row 2, grid 1 -->
				<div class="col-md-4 col-xs-12">
					<div class="widget5">
						<div class="header-image">
							<img src="<?php echo $this->baseUrl('/image/'); ?>head-image2.png" alt="head-image" width="260" height="187">
						</div>
						<div class="widget-header">
							<i class="fa fa-check fa-fw"></i>
							<h1>Integrations</h1>
						</div>
						<div class="widget-content">
							<i class="fa fa-info-circle fa-fw"></i>
							<p>Creative through digital demands speed. You've spent the time creating the ad, app, video or website. Now take the next step and deliver it right.</p>
							<a href="#" class="btn btn-primary">Learn More</a>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-xs-12">
					<div class="widget5">
						<div class="header-image">
							<img src="<?php echo $this->baseUrl('/image/'); ?>head-image3.png" alt="head-image" width="260" height="187">
						</div>
						<div class="widget-header">
							<i class="fa fa-check fa-fw"></i>
							<h1>Mobile</h1>
						</div>
						<div class="widget-content">
							<i class="fa fa-info-circle fa-fw"></i>
							<p>MaxCDN provides powerful tools to get up and running quickly so that you can easily provide CDN to your clientele.</p>
							<a href="#" class="btn btn-primary">Learn More</a>
						</div>
					</div>
				</div>
				<!-- when needed, row 3, grid 1 -->
				<!-- when needed, row 4, grid 1 -->
			</div>			
		</div><!-- ./main content -->