<?php $this->headTitle('Cookie Policy | Vantworks'); ?>

		<!-- main content header -->
		<div class="title-container grey-background">
			<div class="main-title">
				<h1>Cookie Policy</h1>
			</div>
		</div>
		<!-- ./main content header -->

<div class="container">
	<div class="about-us">
		<div class="row">
			<div class="col-md-8">
								
				 <p>This website uses cookies. A cookie is a small file of letters and numbers that we put on your computer if you agree.</p>
				 
				 
				<p>These cookies allow us to distinguish you from other users of the website which helps us to provide you with a good experience when you browse our website and allows us to improve our site.</p>
				
				<h2>Browser Settings</h2>
				<p>Most web browsers allow some control of most cookies through the browser settings.</p>

				<h2>Removing Cookies</h2>
				<p>You can withdraw your consent and remove or block cookies at any time using the settings in your browser, but in some cases, this may impact your ability to use our website.</p>
								
					
			</div><!-- /.col-md-8 - main content -->
			<div class="col-md-4">
				<div class="address-wrap">
				   <h4>Contact Address</h4>
				   <div class="address-details">
						   <p>Vantworks Limited</p>
						   <p>4-5 Bonhill street</p>
						   <p>London, United Kingdom</p>
						   <p>EC2A 4BX</p>
						   <p>Phone: <a href="tel:+442030868255">0203 086 8255</a></p>
						   <p>Email: <a href="mailto:hello@vantworks.co.uk">hello@vantworks.co.uk</a> </p>
					   
					</div> <!-- end agent-details -->
				</div><!-- /.user-profile -->
			</div><!-- /.col-md-4 -->
		</div><!-- /.row -->
	</div><!-- /.about-us -->
</div><!-- /.container -->
