<?php 
		// NOTE: variables $controller and $action are in used throughout this page
		
		$request = Zend_Controller_Front::getInstance()->getRequest();
        $controller = $request->getControllerName();
        $action = $request->getActionName();
		
		if($controller == 'index' && $action =='index' ) {
		$this->headTitle("Vantworks | Web Applications, Business Analytics, Cloud Hosting");
		}	
?>	  

<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' ');
//echo $this->doctype('HTML5'); 
echo $this->doctype('HTML5'); 

//define the meta http-equiv to IE, this should allow for styling of FORM select element in IE7+
$http_equiv="X-UA-Compatible";
$IE_content="IE=edge";
$this->headMeta()->appendHttpEquiv($http_equiv, $IE_content);

//define the meta viewport for front end responsive behaviour
$portcontent="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no";
$portname="viewport";
$this->headMeta($portcontent, $portname);

?>


<?php 
$name = 'description';
$content = "Vantworks is a London based startup that provides digital and business analytics solutions for startups and corporate organisations.";
$this->headMeta($content, $name);

$name = 'keywords';
$content = 'Business intelligence, business analytics, web applications, cloud Hosting, London web development, uxbridege web develoment';
$this->headMeta($content, $name);
?>





<html lang="en">
<head>
<?php echo $this->headMeta(); ?>
<?php echo "\n"; // this is new line command, for headTitle (below) to start in a new line ?>
<?php echo $this->headTitle(); ?>

<!-- Open graph tags -->
<meta property="fb:app_id" content="327634444037550"/>
<meta property="og:url" content="http://www.vantworks.co.uk/"/>
<meta property="og:title" content="Vantworks | Web Applications, Cloud Hosting, Business Analytics"/>
<meta property="og:site_name" content="Vantworks Limited"/>
<meta property="og:type" content="website"/>
<meta property="og:description" content="Vantworks is a London based startup that provides digital and business analytics solutions for startups and corporate organisations."/>
<meta property="og:image" content="http://www.vantworks.co.uk/image/vantwoks-logo.png">

<!-- END Open graph tags -->


<!-- jQuery cdn files -->
<?php $this->headScript()->prependFile('//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js'); ?>
<?php $this->headScript()->appendFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js');?>
<?php $this->headScript()->appendFile($this->baseUrl().'/js/jquery.validate.min.js', 'text/javascript'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/js/scripts.js', 'text/javascript'); ?>





<!-- END links for jQuery ALS scroll -->

<?php $this->headLink()->prependStylesheet("//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"); ?>

<?php $this->headLink()->appendStylesheet("//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"); ?>

<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap-overrides.css'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/styles.css'); ?>

<?php $this->headLink()->headLink(array('rel' => 'icon',
                                  'href' => '/public/favicon.ico'),
								  //'type' => 'image/x-icon',
                                'PREPEND');
								  ?>
								  


	

		<?php //echo data picker in the format 'dd/mm/yy'

		?>
			
<?php // print google fonts ;?>	
<link href='http://fonts.googleapis.com/css?family=Raleway:100,300,400,700|Lato:bold,300,400,700|Montserrat:100,300,400,700|Comfortaa|Oxygen:bold' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,400italic,600,800' rel='stylesheet' type='text/css'>
			
<?php echo $this->headLink();?>


<?php echo $this->jQuery(); ?>

<?php echo $this->headScript();?>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41616141-1', 'vantworks.co.uk');
  ga('send', 'pageview');

</script>



<meta name="google-site-verification" content="m-m_59-1sliet5mcb7YFNWW8NznLqV-vW658SrrEboI" />


</head>
<body>
    
<!-- header -->
<header>
	<div class="container">
		<!-- main navbar -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<!-- EU cookie law, hidden, it's shown with jQuery code if user never saw it before -->
				<div class="alert alert-cookies alert-dismissible hidden">
					<button type="button" class="close eu-cookie-law" data-dismiss="alert"><i class="fa fa-times"></i></button>
					<p>We use cookies to give you the best experience. By continuing to use this site, you agree to our use of cookies. See our <a href="<?php echo $this->url(array('controller'=>'cookies','action'=>'index'), 'default', true);?>">cookie policy.</a></p>
				</div>
				<!-- logo and mobile menu button -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar"><i class="fa fa-bars"></i></button>
					<a class="navbar-brand" href="<?php echo $this->url(array('controller'=>'index','action'=>'index'), 'default', true);?>"><img src="<?php echo $this->baseUrl('/image/'); ?>vantworks-logo.png" alt="Vantworks logo"></a>
				</div>
				<!-- menu container -->
				<div class="collapse navbar-collapse" id="top-navbar">
					<!-- center aligned -->
					<ul class="nav navbar-nav">
						<li class="<?php if($controller == 'solutions' && $action =='index') {echo 'active';}?>"><a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>">SOLUTIONS</a></li>
						<li class="<?php if($controller == 'about' && $action =='why-vantworks') {echo 'active';}?>"><a href="<?php echo $this->url(array('controller'=>'about','action'=>'why-vantworks'), 'default', true);?>">WHY VANTWORKS</a></li>
						<li class="<?php if($controller == 'our-process' && $action =='index') {echo 'active';}?>"><a href="<?php echo $this->url(array('controller'=>'our-process','action'=>'index'), 'default', true);?>">OUR PROCESS</a></li>				
						<li class="<?php if($controller == 'about' && $action =='index') {echo 'active';}?>"><a href="<?php echo $this->url(array('controller'=>'about','action'=>'index'), 'default', true);?>">ABOUT</a></li>
						<li class="<?php if($controller == 'about' && $action =='contact-us') {echo 'active';}?>"><a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>">CONTACT US</a></li>
					</ul>
					<!-- right side buttons -->
					<ul class="nav navbar-nav navbar-right visible-sm visible-md visible-lg">
						<li><a href="tel:+442030868255" class="btn btn-head-signup"><i class="fa fa-phone fa-fw"></i> <b>0203 086 8255</b></a></li>
					</ul>					
					<!-- mobile only right side buttons -->
					<ul class="nav navbar-nav navbar-right visible-xs">
						<li><a href="tel:+442030868255" class="btn btn-head-signup"><i class="fa fa-phone fa-fw"></i> <b>0203 086 8255</b></a></li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- ./main navbar -->
	</div>
</header>
<!-- ./header -->		

 

<?php echo $this->layout()->content; ?>


<!-- footer -->
<footer style="background-color:#F1F1F1;">
	<!-- top footer -->
	<div class="footer-top">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-12">
					<img src="<?php echo $this->baseUrl('/image/'); ?>logo-footer.png" alt="slider 1">
				</div>
				<div class="col-md-3 col-sm-6">
					<h1>Company</h1>
					<ul class="not-styled">
						<li><a href="<?php echo $this->url(array('controller'=>'about','action'=>'index'), 'default', true);?>">About Us</a></li>					
						<li><a href="<?php echo $this->url(array('controller'=>'about','action'=>'why-vantworks'), 'default', true);?>">Why Vantworks?</a></li>
						<li><a href="<?php echo $this->url(array('controller'=>'our-process','action'=>'index'), 'default', true);?>">Our Process</a></li>
						<li><a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>">Contact Us</a></li>
					</ul>
				</div>
				<div class="col-md-3 col-sm-6">
					<h1>Solutions</h1>
					<ul class="not-styled">
						<li><a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'web-applications'), 'default', true);?>">Web Applications</a></li>
						<li><a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'business-analytics'), 'default', true);?>">Business Analytics</a></li>
						<li><a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'digital-marketing'), 'default', true);?>">Digital Marketing</a></li>
						<li><a href="<?php echo $this->url(array('controller'=>'business-website-design','action'=>'index'), 'default', true);?>">Business Website Design</a></li>
					</ul>
				</div>
				<div class="col-md-3 col-sm-12">
					<h1>Social</h1>
					<ul class="not-styled social-icons">
						<li><a href="#"><i class="fa fa-facebook fa-fw"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter fa-fw"></i></a></li>
						<li><a href="#"><i class="fa fa-linkedin fa-fw"></i></a></li>
						<li><a href="#"><i class="fa fa-google-plus fa-fw"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- ./top footer -->


	<!-- bottom footer -->
	<div class="footer-bottom">
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					&nbsp;
				</div>
				<div class="col-md-9">
					<ul class="not-styled footer-links">
						<li><a href="<?php echo $this->url(array('controller'=>'about','action'=>'privacy'), 'default', true);?>">Privacy Policy</a></li>
						<li><a href="<?php echo $this->url(array('controller'=>'cookies','action'=>'index'), 'default', true);?>">Cookie Policy</a></li>
					</ul>
					<p class="small">&copy; <?php echo date('Y');?> Vantworks Limited. All rights reserved. Vantworks Limited is a UK registered company. </p>
				</div>
			</div>
		</div>
	</div>
	<!-- ./bottom footer -->
</footer>
<!-- ./footer -->


</body>

</html>