<?php $this->headTitle('Vantworks | Digital Marketing'); ?>

		<div class="widget-header-banner widget-pg-dm">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						
						<h2 style="color:#1A1A1A;">Get A Business Website That Works</h2>
						<h1 style="color:#1A1A1A; font-weight:400;">Let's Grow Your Business</h1>
					</div>
				</div>
			</div>
		</div>	
		<!-- clients widget -->
		<div class="widget-clients">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
							<h3 class="text-center">Trusted by clients of all sizes</h3>
							<div class="col-xs-6 col-sm-3">
								<a href="#" target="_blank">
									<img src="<?php echo $this->baseUrl('/image/'); ?>tfl_logo.png" alt="tfl logo" width="170" height="50">
								</a>
							</div>
							<div class="col-xs-6 col-sm-3">
								<a href="#" target="_blank">
									<img src="<?php echo $this->baseUrl('/image/'); ?>rbh.png" alt="Royal brompton NHS" width="170" height="50">
								</a>
							</div>	
							<div class="col-xs-6 col-sm-3">
								<a href="#" target="_blank">
									<img src="<?php echo $this->baseUrl('/image/'); ?>aacsl-logo.png" alt="AACSL" width="170" height="50">
								</a>
							</div>										
							<div class="col-xs-6 col-sm-3">
								<a href="#" target="_blank">
									<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
								</a>
							</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ./clients widget -->				
		
		
	
		<!-- main content header -->
		<div class="title-container grey-background" style="background-color:#FFFFFF;">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="main-title">
							<h2>Vantworks provides digital design and analytics <br> solutions 
							that help companies perform higher</h2>
						</div>
					</div>	
				</div>
			</div>			
		</div>
		<!-- ./main content header -->

	<div class="container">
		<div class="about-us">
			<div class="row">
				<div class="col-md-8">
				<h2 style="text-align:center;margin-bottom:30px;">What We Can Do For Your Business</h2>
					<div class="row" style="margin-right:20px;">
						<div class="col-xs-2" style="width:10%;">
						<img src="<?php echo $this->baseUrl('/image/home/'); ?>checkmark.png" width="30" height="30">
						</div>
						<div class="col-xs-10 landpg-list">
							<p style="font-size:24px; font-weight:400;color:#2A9BE1;">Professional Business Websites</p>
							<p>Elevate your brand online with a professionally designed website that actually works.
							</p>
							<ul>
								<li><i class="fa fa-check fa-fw"></i>Responsive website design</li>
								<li>Search engine friendly site</li>
								<li>Engaing design</li>						
							</ul>
								
						</div>
					</div>
					<div class="row" style="margin-right:20px;">
						<div class="col-xs-2" style="width:10%;">
						<img src="<?php echo $this->baseUrl('/image/home/'); ?>checkmark.png" width="30" height="30">
						</div>
						<div class="col-xs-10">
							<p style="font-size:24px; font-weight:400;color:#2A9BE1;">Reach More Customer</p>
							<p>Engaging designs that converts visitors to customers. your prospective customers with exciting design that attracts new customers.
							</p>
							<ul>
								<li>Responsive website design</li>
								<li>Search engine friendly site</li>
								<li>Engaing design</li>						
							</ul>
								
						</div>
					</div>
					<div class="row" style="margin-right:20px;">
						<div class="col-xs-2" style="width:10%;">
						<img src="<?php echo $this->baseUrl('/image/home/'); ?>checkmark.png" width="30" height="30">
						</div>
						<div class="col-xs-10">
							<p style="font-size:24px; font-weight:400;color:#2A9BE1;">Websites that Works</p>
							<p>Elevate your brand online with professional and effective business website.
							</p>
							<ul>
								<li>Responsive website design</li>
								<li>Search engine friendly site</li>
								<li>Engaing design</li>						
							</ul>
								
						</div>
					</div>								
				</div><!-- /.col-md-7 - main content -->
				<div class="col-md-4">
					<div class="login-container">
						<?php if (!isset($this->contact_id)): //Form has not been submitted OR process in About/contactUs action?> 
						
							<h4 class="text-center" style="font-size:25px;font-weight:bold;">Get Your <span style="font-size:30px;font-weight:bold;">20%</span> Offer <br>
							Plus Free Website Evaluation.</h4>
							<p class="text-center">Or Call  <a href="tel:+442030868255">0203 086 8255</a></p>
								
								<?php echo $this->form ;?>
							
							<div class="form-group">
							
								<div class="col-sm-12">
									<p class="small">Please note that by submitting this form, you confirm that you accept our website <a href='<?php echo $this->url(array('controller'=>'about','action'=>'privacy'), 'default', true);?>'>Privacy Policy.</a></p>
								</div>

							</div><!-- /.form-group - terms -->		
						<?php else: ?>

							<?php echo $this->successMessage;  ?> 
				
						<?php endif; ?>
					</div>	
				</div><!-- /.col-md-4 -->
			</div><!-- /.row -->
		</div><!-- /.about-us -->
	</div><!-- /.container -->
