<?php $this->headTitle('Vantworks | Digital Marketing'); ?>

		<div class="widget-header-banner widget-pg-dm">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1 style="color:#1A1A1A; font-weight:400;">Let's Grow Your Business</h1>
						<h2 style="color:#1A1A1A;">With A Professional Website That Works</h2>
						
						<p class="text-center"><a class="btn btn-cta btn-lg">SAVE 20% ON YOUR NEW WEBSITE</a></p>
					</div>
				</div>
			</div>
		</div>	
		<!-- clients widget -->
		<div class="widget-clients">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
							<h3 class="text-center">Trusted by clients of all sizes</h3>
							<div class="col-xs-6 col-sm-3">
								<a href="#" target="_blank">
									<img src="<?php echo $this->baseUrl('/image/'); ?>tfl_logo.png" alt="tfl logo" width="170" height="50">
								</a>
							</div>
							<div class="col-xs-6 col-sm-3">
								<a href="#" target="_blank">
									<img src="<?php echo $this->baseUrl('/image/'); ?>rbh.png" alt="Royal brompton NHS" width="170" height="50">
								</a>
							</div>	
							<div class="col-xs-6 col-sm-3">
								<a href="#" target="_blank">
									<img src="<?php echo $this->baseUrl('/image/'); ?>aacsl-logo.png" alt="AACSL" width="170" height="50">
								</a>
							</div>										
							<div class="col-xs-6 col-sm-3">
								<a href="#" target="_blank">
									<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
								</a>
							</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ./clients widget -->				
		
		
	
		<!-- main content header -->
		<div class="title-container widget-stmnt">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="main-title">
							<h2>Vantworks provides digital design and analytics <br> solutions 
							that drive business results</h2>
							<hr>
						</div>
					</div>	
				</div>
			</div>			
		</div>
		<!-- ./main content header -->
		
	<div class="container landpg">
			<div class="row">
				<div class="col-md-8">
				<div style="background-color:yellow;margin-top:0px;margin-bottom:40px;">
					<h2>Our Helpful Solutions</h2>
				</div>
					<div class="row landpg-row">
						<div class="col-md-6 col-sm-6 landpg-col">
							<span class="icon">
								<i class="fa fa-mobile fa-fw"></i>
							</span>
							<h2>Website Design</h2>
							<p>Elevate your brand online with professionally designed business website that actually works.</p>
							<h4>Features</h4>
							<ul class="landpg-list"> 
								<li><i class="fa fa-check fa-fw"></i>Responsive website design</li>
								<li><i class="fa fa-check fa-fw"></i>Search engine friendly site</li>
								<li><i class="fa fa-check fa-fw"></i>Engaing design</li>						
							</ul>						
						</div>
						<div class="col-md-6 col-sm-6">
							<span class="icon">
								<i class="fa fa-cloud fa-fw"></i>
							</span>
							<h2>Audience Engagement</h2>
							<p>Get engaging digital experience that converts site visitors to customers. Let's build an exciting website for your business.</p>
							<h4>Features</h4>
							<ul class="landpg-list">
								<li><i class="fa fa-check fa-fw"></i>Attract new customers</li>
								<li><i class="fa fa-check fa-fw"></i>Turn prospect to customers</li>
								<li><i class="fa fa-check fa-fw"></i>Enhance customer value </li>						
							</ul>							
						</div>
					</div>	
					<div class="row landpg-row">
							<div class="col-md-6 col-sm-6 landpg-col">
								<span class="icon">
									<i class="fa fa-mobile fa-fw"></i>
								</span>
								<h2>Digital Marketing</h2>
								<p>Elevate your brand online with an affordable and professionally designed website that actually works.</p>
								<h4>Features</h4>
								<ul class="landpg-list"> 
									<li><i class="fa fa-check fa-fw"></i>Responsive website design</li>
									<li><i class="fa fa-check fa-fw"></i>Search engine friendly site</li>
									<li><i class="fa fa-check fa-fw"></i>Engaing design</li>						
								</ul>						
							</div>
							<div class="col-md-6 col-sm-6">
								<span class="icon">
									<i class="fa fa-cloud fa-fw"></i>
								</span>
								<h2>Data Analytics</h2>
								<p>Get engaging digital experience that converts site visitors to customers. Let's build an exciting website for your business.</p>
								<h4>Features</h4>
								<ul class="landpg-list">
									<li><i class="fa fa-check fa-fw"></i>Attract new customers</li>
									<li><i class="fa fa-check fa-fw"></i>Turn prospect to customers</li>
									<li><i class="fa fa-check fa-fw"></i>Enhance customer value </li>						
								</ul>							
							</div>
						</div>						
				</div>	
				<div class="col-md-4">
					<div class="lead-container">
						<?php if (!isset($this->contact_id)): //Form has not been submitted OR process in About/contactUs action?> 
						
							<h4>Get Your <span>20%</span> Offer <br>
							Plus Free Website Evaluation.</h4>
							<p class="text-center">Or Call:  <a href="tel:+442030868255">0203 086 8255</a></p>
								
								<?php echo $this->form ;?>
							
							<div class="form-group">
							
								<div class="col-sm-12">
									<p class="small">Please note that by submitting this form, you confirm that you accept our website <a href='<?php echo $this->url(array('controller'=>'about','action'=>'privacy'), 'default', true);?>'>Privacy Policy.</a></p>
								</div>

							</div><!-- /.form-group - terms -->		
						<?php else: ?>

							<?php echo $this->successMessage;  ?> 
				
						<?php endif; ?>
					</div>	
					
					<!-- testimonial widget -->
					<div class="row reviews-set">
						<!-- testimonial slider -->
						<div class="col-md-12">
						<h3>What Our Customers Say</h3>
							<div class="carousel slide" id="partners-carousel" data-ride="carousel">
								<!-- testimonial content -->
								<div class="carousel-inner">
									<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
									<div class="item active">
										<div class="row">
										
											<div class="col-xs-10 col-xs-offset-1 feedback">
												<p><span>"</span>We successfully launch our new website that clearly highlights our value propositions. Our clients love it. Thanks to Vantworks<span>"</span>
												</p>
												<p style="font-style:normal;">Tunde O, Director, Intuitrics</p>
											</div>
										</div>								
									</div>
									<div class="item">
										<div class="row">
										
											<div class="col-xs-10 col-xs-offset-1 feedback">
												<p><span>"</span>We successfully launch our new website that clearly highlights our value propositions. Our clients love it. Thanks to Vantworks<span>"</span>
												</p>
												<p style="font-style:normal;">Mark A, Director, Intuitrics</p>
											</div>
										</div>								
									</div>									

								</div>
								<!-- ./slider content -->
							</div>
						</div>
						<!-- ./testimonial carousel -->
					</div>
					<!-- testimonial widget-->						
				</div><!-- /.col-md-4 -->				
			</div>	
	</div>	<!-- end container -->	

