<?php $this->headTitle('Vantworks | Digital Marketing'); ?>

		<div class="widget-header-banner widget-pg-dm">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Grow Your Business</h1>
						<h2>With A Professional Website That Works</h2>
						
						<p class="text-center"><a class="btn btn-cta btn-lg">SAVE 20% ON YOUR WEBSITE</a></p>
					</div>
				</div>
			</div>
		</div>	
		<!-- clients widget -->
		<div class="widget-clients">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
							<h3 class="text-center">Trusted by clients big and small</h3>
							<div class="col-xs-6 col-sm-3">
									<img src="<?php echo $this->baseUrl('/image/'); ?>tfl_logo.png" alt="tfl logo" width="170" height="50">
							</div>
							<div class="col-xs-6 col-sm-3">
									<img src="<?php echo $this->baseUrl('/image/'); ?>rbh.png" alt="Royal brompton NHS" width="170" height="50">
							</div>	
							<div class="col-xs-6 col-sm-3">
									<img src="<?php echo $this->baseUrl('/image/'); ?>aacsl-logo.png" alt="AACSL" width="170" height="50">
							</div>										
							<div class="col-xs-6 col-sm-3">
									<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
							</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ./clients widget -->				
		
		
	
		<!-- main content header -->
		<div class="title-container widget-stmnt">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="main-title">
							<h2>Vantworks provides digital design and analytics <br> solutions 
							that drive business results</h2>
							<hr>
						</div>
					</div>	
				</div>
			</div>			
		</div>
		<!-- ./main content header -->
		
		<!-- widget with three options -->
		<div class="widget2 container">
			<div class="row">
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-mobile fa-fw"></i>
					</span>
					<h2>Digital Design</h2>
					<p>Vantworks has experience in building profesional and responsive web applications.</p>
				</div>
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-cloud fa-fw"></i>
					</span>
					<h2>Digital Marketing</h2>
					<p>Need to launch and scale your applications without limit on the cloud? Vantworks can help.</p>
				</div>
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-bar-chart fa-fw"></i>
					</span>
					<h2>Business Analytics</h2>
					<p>Generate business insights from enterprise data in order to gain a competitive edge filler here.</p>
				</div>				
			</div>
		</div>
		
		<div class="container cta-container">
			<div class="row">
				<div  class="col-md-12">
					<p class="text-center"><a class="btn btn-cta btn-lg">GET YOUR 20% OFFER</a></p>
				</div>
			</div>
		</div>
			


	<div class="brand-red benefits-box">			
		<div class="container">
			<div class="benefits">			
				 <div class="row">
					<div class="col-sm-6">
						<h2>Website that Works</h2>
						<p>More than just a web presence, we create website that helps to achieve your business objectives.</p>
						<div class="row">
							<div  class="col-md-12">
								<p><a class="btn btn-cta btn-lg">GET YOUR 20% OFFER</a></p>
							</div>
						</div>						
					</div>
					<div class="col-sm-6">
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- testimonial content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-md-12">
											<img class="img-responsive" src="<?php echo $this->baseUrl('/image/landing/'); ?>rideblisshome2.png" width="100%" height="100%">
										</div>
									</div>								
								</div>
								<div class="item">
									<div class="row">
										<div class="col-md-12">
											<img class="img-responsive" src="<?php echo $this->baseUrl('/image/landing/'); ?>aacslhome2.png" width="100%">		
										</div>
									</div>				
								</div>
							</div>
							<!-- ./slider content -->
						</div>
					</div>
				 </div><!-- /.row -->
			</div><!-- ./benefits -->
		</div><!-- /.container -->	
	</div>	


		<div class="container widget-lander-features">
			<div class="row">
				<div class="col-md-12 lander-call">
					<h2>Benefits to help you grow</h2>
					<p>We would love to be your partner for growth</p>
				</div>
					
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-mobile fa-fw"></i>
					</span>
					<h4>Business Analytics</h4>
					<p>Vantworks has experience in building profesional and responsive web applications.</p>
				</div>
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-cloud fa-fw"></i>
					</span>
					<h4>Business Analytics</h4>
					<p>Need to launch and scale your applications without limit on the cloud? Vantworks can help.</p>
				</div>
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-bar-chart fa-fw"></i>
					</span>
					<h4>Business Analytics</h4>
					<p>Generate business insights from enterprise data in order to gain a competitive edge filler here.</p>
				</div>				
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-mobile fa-fw"></i>
					</span>
					<h4>Business Analytics</h4>
					<p>Vantworks has experience in building profesional and responsive web applications.</p>
				</div>
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-cloud fa-fw"></i>
					</span>
					<h4>Business Analytics</h4>
					<p>Need to launch and scale your applications without limit on the cloud? Vantworks can help.</p>
				</div>
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-bar-chart fa-fw"></i>
					</span>
					<h4>Business Analytics</h4>
					<p>Generate business insights from enterprise data in order to gain a competitive edge filler here.</p>
				</div>				
			</div>
		</div>	
		
		<div class="container cta-container">
			<div class="row">
				<div  class="col-md-12">
					<p class="text-center"><a class="btn btn-cta btn-lg">GET YOUR 20% OFFER</a></p>
				</div>
			</div>
		</div>

		<!-- testimonial widget -->
		<div class="widget-review">
			<div class="container">
				<div class="row">
					<!-- testimonial slider -->
					<div class="col-md-12 reviews">
					<h3>We Make Our Customers Happy</h3>
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- testimonial content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-md-8 col-md-offset-2">
											<p class="text-center">"We successfully launch our new website that clearly highlights our value propositions. Our clients love it. Thanks to Vantworks"
											</p>
											<p class="text-center">Chuks O, Director, Intuitrics</p>
										</div>
									</div>								
								</div>
								<div class="item">
									<div class="row">
										<div class="col-md-8 col-md-offset-2">
											<p class="text-center">"Thanks to Vantworks, we turned what could have been a million-dollar mistake into a major win both for us and our users."
											</p>
											<p class="text-center">Tunde O, Director, Intuitrics</p>
										</div>
									</div>				
								</div>
							</div>
							<!-- ./slider content -->
						</div>
					</div>
					<!-- ./testimonial carousel -->
				</div>
			</div>
		</div>
		<!-- testimonial widget-->			