<?php $this->headTitle('Frequently Asked Questions'); ?>




<div class="container" style="padding-top:40px">
	<div class="trust-safety">
	
		<?php  $ride_date = date('d/m/Y'); // Get $ride_date to use for 'ride sharing journeys' link below ?>
		
		<h1>Frequently Asked Questions</h1>
		<h2>What is AACSL?</h2>
		<p>AACSL is a professional accountant for small, medium and large businesses.</p>
		<h2>Do you advise on Tax?</h2>
		<p>Yes.</p>
		<h2>Do you work on PAYE?</h2>
		<p>Yes. We manage and send your employees payslips and the required HMRC deductions.</p>
		<h2>Do you send reminders?</h2>
		<p>Yes, to help you comply with HMRC anbd Companies House key dates.</p>

	</div><!-- /.trust-safety -->
</div><!-- /.container -->