<?php $this->headTitle('About Vantworks | Web Applications, Cloud Hosting, Business Analytics'); ?>

		<!-- main content header -->
		<div class="widget-container grey-background">
			<div class="main-title">
				<h1>About Vantworks</h1>
			</div>
		</div>
		<!-- ./main content header -->

<div class="container">
	<div class="about-us">
		<div class="row">
			<div class="col-md-8">
								
				 <p>Vantworks is digital startup that utilizes latest technologies to build web applications and business analytics solutions for entreprenuers, startups and corporate organisations. We help our customers to achieve their successful IT strategies by building creative bespoke solutions that align with business goals.</p>
				 <p>Although we are a startup business, we are passionate, agile and keep seeking innovative ways to enable our clients achieve their bottom line better, faster and cheaper.</p>
				 <p>Our goal is to enable small and medium enterprises compete favourably in the digital business environment. </p>
				 <p> Our creative team is passionate and knowledgeable in providing <a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>">solutions</a> that broadly include <a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#webApplications">web applications</a>, <a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#businessAnalytics">business analytics</a>, and <a href="<?php echo $this->url(array('controller'=>'solutions','action'=>'index'), 'default', true);?>#cloudHosting">cloud hosting</a> to deliver real business value to our growing clients.</p>
				 <p>Vantworks can improve your business performance by helping you  enhance existing customers as well as acquire and attract potential new customers.</p>
				 <p>You could <a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>">drop us a line here</a>. Let's work together. </p>
								
					
			</div><!-- /.col-md-8 - main content -->
			<div class="col-md-4">
				<div class="address-wrap">
				   <h4>Contact Address</h4>
				   <div class="address-details">
						   <p>Vantworks Limited</p>
						   <p>4-5 Bonhill street</p>
						   <p>London, United Kingdom</p>
						   <p>EC2A 4BX</p>
						   <p>Phone: <a href="tel:+442030868255">0203 086 8255</a></p>
						   <p>Email: <a href="mailto:hello@vantworks.co.uk">hello@vantworks.co.uk</a> </p>
					   
					</div> <!-- end agent-details -->
				</div><!-- /.user-profile -->
			</div><!-- /.col-md-4 -->
		</div><!-- /.row -->
	</div><!-- /.about-us -->
</div><!-- /.container -->
