<?php $this->headTitle('Privacy Policy | Vantworks'); ?>

		<!-- main content header -->
		<div class="widget-container grey-background">
			<div class="main-title">
				<h1>Privacy Policy</h1>
			</div>
		</div>
		<!-- ./main content header -->

<div class="container">
	<div class="about-us">
		<div class="row">
			<div class="col-md-8">
				<p>Your privacy is important to us. This Vantworks privacy policy explains generally how we receive personal information about you and how we use such information.</p>
				<h2>What we mean by "personal information"</h2>
				<p>By "personal information" we mean information which identifies you, like your name or email address. Any information that falls outside of this definition is non-personal information.</p>
			
				<h2>Personal information we collect about you</h2>
				<p>You can use our websites without disclosing any personal information of yourself.</p>
				<p>By providing your details in form fields, such as name email address, you make it possible for Vantworks to provide you personalised service(s) that you have selected.</p>
				<p>We will only request information we need to provide you the service(s) you have requested.</p>
				<hr class="hr_divider">
				<h2>How we use your information</h2>
				<p>We use the information we collect to provide you our services you requested and to communicate with you. We will only share your personal information outside our organisation in the following circumstances:</p>
				<ul>
					<li>When you have consented or directed us to share the information.</li>
					<li>With service providers or affiliate companies who perform services on our behalf.</li>
					<li>In order to satisfy any requirement under the law or to protect our rights or prevent any concerns relating to fraud or security.</li>
					<li>In the event of a merger or sale of all or part of our business whereby personal information may be transferred as an asset of the business.</li>
				</ul>
				<p>We may share with third parties aggregate information or information that does not personally identify you.</p>
				<hr class="hr_divider">
				<h2>Third parties</h2>
				<p>We use third parties to monitor web traffic and/or serve advertisements on our website and these third parties may use parties or other means to help measure the effectiveness of their services. Our website may also include links to other unrelated websites and/or contact forms to other unrelated parties which may collect personal information.  Our privacy policy does not extend to these third parties or other websites and we recommend that users refer directly to these parties regarding their privacy policies before supplying personal details to these companies.</p>
				<hr class="hr_divider">
				<h2>Safety and security</h2>
				<p>Personal information is processed and stored in our databases and we have taken reasonable steps to secure and protect the information under our control, including establishing processes to prevent unauthorized access or disclosure of this information. However, whilst we make every effort to ensure the security of your information, we are unable to guarantee the protection of the information from misuse, accidental disclosure or unauthorised acts by others. Information provided by you may be stored or processed outside the UK.</p>
				<hr class="hr_divider">
				<h2>Cookie policy</h2>
				<p>A cookie is a piece of text that a website transfers to your computer's hard disk so it can remember who you are. Cookies are generally used to monitor how a website is used and improve your online experience. They do not give us access to the rest of your computer and are not used to identify you personally. </p>
				<p>When browsing our website, we may place one or more cookies. This helps us to improve our services by personalising information you may want. You may adjust the settings on your browser to refuse cookies but some of the services may not work if you do so. We may also log information from your computer including the existence of cookies, your IP address and information about your browser program in order to allow us to diagnose problems, administer and track your usage of our websiste.</p>
				<hr class="hr_divider">
				<h2>Changes to privacy policy</h2>
				<p>We may occasionally update this statement. Your continued use of the site will mean that you accept those revisions.</p>
				<p>For further enquiries about our privacy policy, please <span class="user-login alt"><a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>">Contact Us</a>.</span></p>
			</div>	
			<div class="col-md-4">
				<div class="address-wrap">
				   <h4>Contact Address</h4>
				   <div class="address-details">
						   <p>Vantworks Limited</p>
						   <p>4-5 Bonhill street</p>
						   <p>London, United Kingdom</p>
						   <p>EC2A 4BX</p>
						   <p>Phone: <a href="tel:+442030868255">0203 086 8255</a></p>
						   <p>Email: <a href="mailto:hello@vantworks.co.uk">hello@vantworks.co.uk</a> </p>
					   
					</div> <!-- end agent-details -->
				</div><!-- /.user-profile -->
			</div><!-- /.col-md-4 -->	
		</div><!-- /.row -->
	</div><!-- /.about-us -->
	
</div><!-- /.container -->
