<?php $this->headTitle('Terms of Use'); ?>

<?php //echo date picker in the format 'dd/mm/yyyy'
			
			$this->headScript()->appendScript('
                                    $(document).ready(function() {
									$( "#ride_date" ).datepicker({dateFormat: "dd/mm/yy" , 
									showOtherMonths: true, 			changeMonth: false, minDate: 0,
			changeYear: false, defaultDate: +7}).attr("readOnly", "true");
									});',
									$type='text/javascript') 
									
?>

<?php $script='$(document).ready(function() {
function log( message ) {
			$( "<div/>" ).text( message ).prependTo( "#log" );
			$( "#log" ).scrollTop( 0 );
		}

		$( "#departure, #destination" ).autocomplete({
			source: "/rides/destination",
			minLength: 2,
			select: function( event, ui ) {
				log( ui.item ?
					"Selected: " + ui.item.value + " aka " + ui.item.id :
					"Nothing selected, input was " + this.value );
			}
		});
	});'; ?>
<?php $this->headScript()->appendScript($script, $type='text/javascript') ;?>


<div class="container">
	<div class="search-form-container alt">
		<?php echo $this->ridesForm; ?>
	</div><!-- /.search-form-container alt -->
</div><!-- /.container -->


<div class="container">
	<div class="terms-of-use">
		<h1>Terms of Use</h1>
		<p>By using this website and the services contained therein ('Services') you agree to comply with and be bound by the following terms and conditions ('Terms of Use'). If you do not agree to and accept these Terms of Use, you should not use this website. All references within these Terms of Use to 'we/us/our' refer to Ridebliss.</p>
		<hr class="hr_divider">
		<h2>Restrictions on Use</h2>
		(1) With respect to Your participation on the Site or through the Services, You agree that You will not:
		<ul>
			<li>Use the Services for any criminal or unlawful purposes and intentions such as '419', kidnapping or 'One Chance'</li>
			<li>Impersonate any person or entity </li>
			<li>'Stalk' or otherwise harass or disrespect any person</li>
			<li>Transmit any material designed to interrupt, damage, destroy or limit the functionality of our website or the Services</li>
			<li>Use any automated software to view the Services without consent and to only access our Services manually</li>
			<li>Use the Services other than for your own personal use or for sharing information available on the website</li>
			<li>Attempt to copy our data or reverse engineer our processes without our consent</li>
			<li>Use our Services in any manner that is illegal, immoral or harmful to us</li>
			<li>Use our Services in breach of any policy or other notice on our website</li>
			<li>Remove or alter any copyright notices that appear on our website</li>
			<li>Publish any material that may encourage a breach of any relevant laws or regulations</li>
			<li>Interfere with any other user's enjoyment of our website or the Services</li>
			<li>Transmit materials protected by copyright without the permission of the owner</li>
			<li>Conduct yourself in an offensive or abusive manner whilst using our website or the Services</li>
		</ul>
		(2) You further agree that Your Information and Your interactions on the Site shall not:
		<ul>
			<li> be false, inaccurate or misleading </li>
			<li> infringe any third party's rights, including but not limited to: intellectual property rights, copyright, patent, trademark, trade secret or other proprietary rights or rights of publicity or privacy </li>
			<li> violate any applicable law, statute, ordinance or regulation </li>
			<li> be defamatory, trade libelous, abusive, obscene, profane, offensive, sexually oriented, threatening, harassing, racially offensive or illegal material </li>
			<li> contain any offensive anatomical or sexual references, or offensive sexually suggestive or connotative language </li>
			<li> include in Your Information any telephone numbers, street addresses, last names, URL's or E-mail addresses other than where explicitly asked for it in the Your registration and profile section </li>
			<li> contain any viruses, Trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information </li>
			<li> create liability for us </li> and
			<li> link directly or indirectly to any other websites. You further agree that You will not transfer, use, or sell Your Ridebliss.com account and/or ID to any another party. We reserve the right, but We have no obligation, to reject any Participant that does not comply with these prohibitions </li>
		</ul>
		(3) With respect to your vehicle, if you are a driver, you further agree that:
		<ul>
			<li> Your driving license is valid for the vehicle you are driving </li>
			<li> Your vehicle documents are accurate and valid as required by the applicable Nigeria laws  </li>
			<li> Your vehicle is in good shape for the journey you are embarking on </li>
			<li> You will observe applicable road and driving laws </li>
		</ul>
		(4) With regards  tyour dealings with other members, you further agree that:
		<ul>
			<li> You will not abuse the human rights of other members of this online community </li>
			<li> Your will not disclose personal travel information of other members for unlawful intention</li>
			<li> Your will respect other members time, once travel arangements have been confirmed </li>
		</ul>
		<hr class="hr_divider">
		<h2>Insurance cover </h2>
		<ul>
			<li> At the moment, we do not provide vehicle or life insurance cover to drivers or passengers on journeys arranged via our services </li>
			<li> We shall not be held responsible for any unforeseen incident or accident caused by the driver or passenger during any journey arranged through our service </li>
			<li>It is the sole responsibility of users of our services to take personal insurance policy for themslves or vehicles  </li>
		</ul>
		<hr class="hr_divider">
		<h2>Registration and security</h2>
		<p>You must be over eighteen years of age to register on our website and must ensure that the details provided by you on registration are true, accurate, current and complete. It is your responsibility to update and inform us of any changes to the details provided on registration. Although certain parts of our website may be used by anyone who visits without requiring registration, some of the Services require you to register in order to enable us to verify your identity.</p>
		<p>By registering with the service, you agree that we can send you emails about your account, other Ridebliss services and occasional third party offers. You can manage your communication preferences or unsubscribe from communications at any time via the MyRidebliss section of the website.</p>
		<p>When registering, you will be asked to create a password and will be responsible for maintaining the confidentiality of your password and restricting access to your computer, as you will be accountable for any activities conducted under your password. If you believe that someone has accessed your account without authorisation, please contact us immediately.</p>
		<hr class="hr_divider">
		<h2>Materials you provide</h2>
		<p>By submitting content on our website or otherwise providing content to us in connection with the Services ('Materials'), you grant us a royalty-free, perpetual, irrevocable and non-exclusive right and license to (a) use, reproduce, distribute, display, modify and edit these Materials in connection with the Services and (b) sublicense these rights. We will not pay you any fees for these Materials and reserve the right in our sole discretion to remove or edit them at any time. You also warrant and represent that you have all rights necessary to grant us these rights. We permit you to post Materials on our website in accordance with our procedures provided that the content is not illegal, obscene, abusive, threatening, defamatory or otherwise objectionable to us.</p>
		<hr class="hr_divider">
		<h2>Your responsibilities</h2>
		<p>We are not a transportation company. We provide a service whereby private drivers may post and offer empty car seats with other members of this community heading to similar destination. You may view their journey details ('Details') together with other content hosted and developed by us. You may also request to have a ride with them. Drivers are responsible for preparing the Details and arranging meetup with potential riders. We provide a free secured email communications service between drivers and riders. We do not participate in any part of the payment transaction.</p>
		<p>Details are hosted by us in good faith but are produced directly by drivers and have not been verified by us. You are responsible for making your own enquiries and we provide no guarantee and accept no responsibility for the accuracy or completeness of any information contained within the Details.</p>
		Although, we conduct our basic checks and promote a trusted ride sharing community:
		<ul>
			<li>You are responsible for further checking, confirming and satisfying yourself as to the accuracy of any Details.</li>
			<li>You are responsible for ensuring that you act in good faith towards any other parties.</li>
			<li>You are responsible as a driver for accepting passengers that will share rides with you.</li>
			<li>You are responsible as a passenger for chosing which driver to ride with.</li>
		</ul>
		<hr class="hr_divider">
		<h2>Availability of website</h2>
		<p>We strive to ensure that our website and the Services are available to you at all times but cannot guarantee that either the website or the Services will operate continuously, without interruptions or be fault free. On occasion, necessary maintenance or upgrade work requires us to make the website and the Services unavailable without notice, but we aim to keep downtime to a minimum. We accept no liability for any interruption or loss of service. We reserve the absolute right to alter, suspend or discontinue any part of our website or the Services, including your access to it.</p>
		<hr class="hr_divider">
		<h2>Third parties</h2>
		<p>Our website may contain links to third party products, services and/or websites that are not affiliated with us. We have no control over the products, services or websites of these third parties and we do not guarantee or take responsibility for them. Our website may also contain advertising from third parties and we are not responsible for any misleading or inaccurate advertisements which are the sole responsibility of the advertiser. Any links or advertisements on our website should not be taken as an endorsement by us of any kind. Furthermore, our website contains data provided by third parties and we accept no responsibility for any inaccuracies in this material. You agree to release us from any claims or disputes of any kind arising from or in any way connected to such disputes with third parties.</p>
		<hr class="hr_divider">
		<h2>Intellectual property</h2>
		<p>The Services and all content on our website, including but not limited to design, copy, search results, images, graphics, structure, layouts and the underlying software code are protected by copyright and trademarks and are subject to the intellectual property rights of Ridebliss.com and its licensors. Our logos together with our trademarks and/or service marks may not be copied or reproduced without our prior written consent. All rights are reserved, except for the limited licensed rights expressly granted below.</p>
		<p>You may not reproduce, republish, transmit or distribute any material or information on our website without our prior consent. However, you are granted a limited right to access the Services and retrieve, display and print content pages for your own personal, non-commercial use only. We reserve the right, in our sole discretion and without notice to you, to terminate your licence to use our Services and to prevent future access by you to our website.</p>
		<hr class="hr_divider">
		<h2>Disclaimer</h2>
		<p>The Services are provided on an 'as is' and 'as available' basis and we make no representations or warranties of any kind, either express or implied. You expressly agree that your use of our website and the Services is at your sole risk and we expressly disclaim any and all warranties, either express or implied, including without limitation warranties as to quality, suitability for any purpose, compatibility, reliability, accuracy, completeness, timeliness, access or use. We accept no responsibility and make no guarantee that the Services will be free from faults, errors and/or omissions. It is your sole responsibility to evaluate the quality, suitability, accuracy, completeness and reliability of the Services or any information provided.</p>
		<p>Journey itinerary and other information provided on our website are intended for information and marketing purposes, whilst displayed in good faith, we will not in any circumstances accept responsibility for their accuracy. The journey detail pages on our website are provided by the driver, and can be withdrawn anytime at their own descritions. It is the responsibility of drivers to choose the prospective passengers to accept ride requests from. In the same vain, it is the responsibility of prospective passengers to choose the driver to travel with, by requesting for a ride.</p>
		<hr class="hr_divider">
		<h2>Limitation of liability</h2>
		<p>In no event shall we nor any of our officers, shareholders, directors, employees, agents or suppliers be liable for any loss or direct, indirect, consequential, incidental, special or any other damages arising from your use of the Services. Should you not agree with any part of these Terms of Use or have any dispute or claim against us or our suppliers with respect to these Terms of Use or the Services, your sole and exclusive remedy will be to discontinue using the Services.</p>
		<p>Notwithstanding the foregoing, nothing in this clause is intended to limit any statutory rights you may have as a consumer which may not be excluded nor in any way to exclude or limit our liability to you for personal injury or death caused by our negligence.</p>
		<hr class="hr_divider">
		<h2>Indemnification</h2>
		<p>You agree to indemnify, defend and hold us and our affiliated companies, shareholders, officers, directors, employees, agents or suppliers harmless from any and all claims or demands, made by any third party due to or arising out of your use of the Services, the violation of these Terms of Use by you, or the infringement by you of any intellectual property or other right of any other person or entity.</p>
		<hr class="hr_divider">
		<h2>Changes to Terms of Use</h2>
		<p>We reserve the right in our sole discretion to change these Terms of Use at any time without prior notice to you. Any changes will be posted on our website and become effective at the time of posting. Your continued use of the Services after the effective date of such changes will constitute acceptance of and agreement to any such changes. We reserve the right to modify, suspend or discontinue all or part of the Services at any time to you and/or others, with or without notice. We shall not be liable to you or any other party should we exercise our right to modify, suspend or discontinue all or part of the Services.</p>
		<hr class="hr_divider">
		<h2>Applicable law</h2>
		<p>These Terms of Use shall be governed by and construed in accordance with Nigerian law and the parties agree that any disputes will be settled in Nigerian courts, save that we may take action in any relevant jurisdiction to enforce our intellectual property rights. Should any provision of these Terms of Use be determined to be invalid or unenforceable by any court having competent jurisdiction, then the invalid or unenforceable provision will be replaced with a provision that reflects the intent of the original provision, to the extent permitted by applicable law and all other provisions of these Terms of Use shall remain in full force and effect.</p>
		<hr class="hr_divider">
		<h2>General</h2>
		<p>The headings in these Terms of Use are solely used for convenience and have no legal or contractual significance. We may assign this Agreement, in whole or in part, at any time without notice to you and upon such assignment will be relieved of any further obligation under these Terms of Use. You may not assign, transfer or sublicense your rights, if any, under these Terms of Use. Our delay or failure to exercise or enforce any right or provision of these Terms of Use with respect to a breach by you or others shall not constitute or be construed as a waiver of such right to act. We shall not be responsible for any breach of these Terms of Use caused by circumstances beyond our control.</p>
		<p>These Terms of Use together with the <span class="user-login alt"><a href="<?php echo $this->url(array('controller'=>'about','action'=>'privacy'), 'default', true);?>">Privacy Policy</a></span> constitute the entire agreement between you and us with respect to the Services and supersede any and all prior agreements and understandings between you and us.</p>
		<p>For further enquiries about our Term of Use, please <span class="user-login alt"><a href="<?php echo $this->url(array('controller'=>'about','action'=>'contact-us'), 'default', true);?>">Contact Us</a>.</span></p>
		<p>&nbsp;</p>
		<p>Ridebliss</p>
		<p>Ogudu</p>
		<p>Lagos, Nigeria</p>
		<p>Phone: +234 814 541 7911</p>
		<p>Email: hello@ridebliss.com</p>
	</div><!-- /.terms-of-use -->
</div><!-- /.container -->