<?php $this->headTitle('Business Website Design | Vantworks'); ?>

		<div class="widget-header-banner widget-pg-dm">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Grow Your Business</h1>
						<h2>With A Professional Website That Works</h2>
						
						<p class="text-center"><a class="btn btn-cta btn-lg" href="<?php echo $this->url(array('controller'=>'business-website-design','action'=>'get-offer'), 'default', true);?>">SAVE 20% ON YOUR WEBSITE</a></p>
					</div>
				</div>
			</div>
		</div>	
		<!-- clients widget -->
		<div class="widget-clients">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
							<h3 class="text-center">Trusted by clients big and small</h3>
							<div class="col-xs-6 col-sm-3">
									<img src="<?php echo $this->baseUrl('/image/'); ?>tfl_logo.png" alt="tfl logo" width="170" height="50">
							</div>
							<div class="col-xs-6 col-sm-3">
									<img src="<?php echo $this->baseUrl('/image/'); ?>rbh.png" alt="Royal brompton NHS" width="170" height="50">
							</div>	
							<div class="col-xs-6 col-sm-3">
									<img src="<?php echo $this->baseUrl('/image/'); ?>aacsl-logo.png" alt="AACSL" width="170" height="50">
							</div>										
							<div class="col-xs-6 col-sm-3">
									<img src="<?php echo $this->baseUrl('/image/'); ?>ridebliss-logo.png" alt="Ridebliss" width="170" height="50">
							</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ./clients widget -->				
		
		
	
		<!-- main content header -->
		<div class="title-container widget-stmnt">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="main-title">
							<h2>Vantworks provides website design and analytics <br> solutions 
							that drive business results</h2>
							<hr>
						</div>
					</div>	
				</div>
			</div>			
		</div>
		<!-- ./main content header -->
		
		<!-- widget with three options -->
		<div class="widget2 container">
			<div class="row">
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-mobile fa-fw"></i>
					</span>
					<h2>Website Design</h2>
					<p>We build enterprise website design to improve your brand visibility and drive business growth.</p>
				</div>
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-cloud fa-fw"></i>
					</span>
					<h2>Digital Marketing</h2>
					<p>Data-driven marketing solutions to reach more audiences, convert visitors and improve your sales pipeline.</p>
				</div>
				<div class="col-md-4">
					<span class="icon">
						<i class="fa fa-bar-chart fa-fw"></i>
					</span>
					<h2>Business Intelligence</h2>
					<p>Make informed business decisions through a better understanding of your enterprise data and web analytics.</p>
				</div>				
			</div>
		</div>
		
		<div class="container cta-container">
			<div class="row">
				<div  class="col-md-12">
					<p class="text-center"><a class="btn btn-cta btn-lg" href="<?php echo $this->url(array('controller'=>'business-website-design','action'=>'get-offer'), 'default', true);?>">GET YOUR 20% OFFER</a></p>
				</div>
			</div>
		</div>
			


	<div class="brand-red benefits-box">			
		<div class="container">
			<div class="benefits">			
				 <div class="row">
					<div class="col-sm-6">
						<h2>Websites that work</h2>
						<p>More than just web presence, we build web applications to achieve your business objectives using design and technology. Whether you need to engage more prospects or increase sales, Vantworks is happy to help.</p>
						<div class="row">
							<div  class="col-md-12">
								<p><a class="btn btn-cta btn-lg" href="<?php echo $this->url(array('controller'=>'business-website-design','action'=>'get-offer'), 'default', true);?>">GET YOUR 20% OFFER</a></p>
							</div>
						</div>						
					</div>
					<div class="col-sm-6">
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- testimonial content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-md-12">
											<img style="border:1px solid #444;box-shadow:0 0 3px black" class="img-responsive" src="<?php echo $this->baseUrl('/image/landing/'); ?>rideblisshome2.png" width="100%" height="100">
										</div>
									</div>								
								</div>
								<div class="item">
									<div class="row">
										<div class="col-md-12">
											<img style="border:1px solid #444;box-shadow:0 0 3px black" class="img-responsive" src="<?php echo $this->baseUrl('/image/landing/'); ?>aacslhome2.png" width="100%" height="100">		
										</div>
									</div>				
								</div>
							</div>
							<!-- ./slider content -->
						</div>
					</div>
				 </div><!-- /.row -->
			</div><!-- ./benefits -->
		</div><!-- /.container -->	
	</div>	


		<div class="container widget-lander-features">
			<div class="row">
				<div class="col-md-12 lander-call">
					<h2>Benefits to help you grow</h2>
					<p>We would love to be your growth partner</p>
				</div>
					
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-desktop fa-fw"></i>
					</span>
					<h4>Website Design</h4>
					<p>Professionally designed websites that improve your corporate image and also deliver real business value.</p>
				</div>
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-mobile fa-fw"></i>
					</span>
					<h4>Web Application</h4>
					<p>We build high-performance web applications to support your business processes and marketing efforts.</p>
				</div>
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-pencil fa-fw"></i>
					</span>
					<h4>UX/UI Design</h4>
					<p>Conversion centered design to delight customers, improve brand image and <br>engage more visitors.</p>
				</div>				
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-search fa-fw"></i>
					</span>
					<h4>Search Engine Optimisation</h4>
					<p>Get higher search visibility and drive growth for your business with search engine optimised websites.</p>
				</div>
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-shopping-cart fa-fw"></i>
					</span>
					<h4>Online Marketing</h4>
					<p>Data-driven digital marketing strategies to increase awareness and reach more customers.</p>
				</div>
				<div class="col-md-4 col-sm-6">
					<span class="icon">
						<i class="fa fa-bar-chart fa-fw"></i>
					</span>
					<h4>Data Analytics</h4>
					<p>Use data analytics to better understand your marketing campaign for improved performance.</p>
				</div>				
			</div>
		</div>	
		
		<div class="container cta-container">
			<div class="row">
				<div  class="col-md-12">
					<p class="text-center"><a class="btn btn-cta btn-lg" href="<?php echo $this->url(array('controller'=>'business-website-design','action'=>'get-offer'), 'default', true);?>">GET YOUR 20% OFFER</a></p>
				</div>
			</div>
		</div>

		<!-- testimonial widget -->
		<div class="widget-review">
			<div class="container">
				<div class="row">
					<!-- testimonial slider -->
					<div class="col-md-12 reviews">
					<h3>We Make Our Customers Happy</h3>
						<div class="carousel slide" id="partners-carousel" data-ride="carousel">
							<!-- testimonial content -->
							<div class="carousel-inner">
								<!-- single slider contains four partners, this way we duplicate the doodle.com's effect -->
								<div class="item active">
									<div class="row">
										<div class="col-md-8 col-md-offset-2 text-center">
											<p><em>"We successfully launched our new website that clearly highlights our value propositions. Our clients love it. Thanks to Vantworks."</em>
											</p>
											<p><strong>Rasheed S., Director, AASCL Accountants</strong></p>
										</div>
									</div>								
								</div>
								<div class="item">
									<div class="row">
										<div class="col-md-8 col-md-offset-2 text-center">
											<p><em>"Vantworks always deliver quality web hosting service for my business. I have come to rely on them as my technology partner for growth."</em>
											</p>
											<p><strong>Tunde O., Director, Intuitrics</strong></p>
										</div>
									</div>				
								</div>
							</div>
							<!-- ./slider content -->
						</div>
					</div>
					<!-- ./testimonial carousel -->
				</div>
			</div>
		</div>
		<!-- testimonial widget-->			