<?php $this->headTitle('Offer Received | Vantworks'); ?>

		<!-- main content header -->
		<!-- slider / carousel -->
		<div class="carousel slide" id="main-carousel" data-ride="carousel">
			<!-- indicators - circles on the bottom -->


			<!-- slider content -->
			<div class="carousel-inner">
				<div class="item active">
					<div class="item-image">
						<img src="<?php echo $this->baseUrl('/image/'); ?>balloon-dark.jpg" alt="slider 1">
					</div>
					<div class="container">
						<div class="carousel-caption">
							<h1>Thanks for Your Interest</h1>
							<h2>Let's build a shinning new business website</h2>
						</div>
					</div>
				</div>
			</div>
			<!-- ./slider content -->
			<div class="title-container grey-background">
				<div class="main-title">
					<h3 class="text-center">Take your business to the next level.</h3>
				</div>
			</div>			

		</div>
		<!-- ./main content header -->

<div class="container">
	<div class="about-us">
		<div class="row">
			<div class="col-md-12">
								
				
					<h2>Offer Received </h2>

								<p>
									<?php echo $this->first_name. ', thanks for requesting your offer. We will contact you within three working hours.'; ?>
								</p>								


				
					
	
					
					
			</div><!-- /.col-md-12 - main content -->
		</div><!-- /.row -->
	</div><!-- /.about-us -->
</div><!-- /.container -->
