<?php $this->headTitle('Offer Received | Vantworks'); ?>

		<!-- main content header -->
		<div class="widget-container brand-blue-bkg" style="background-color:#2A9BE1;">
			<div>
				<h1>Thank You.</h1>
				<h2>We'll Get In Touch Shortly</h2>
			</div>
		</div>
		<!-- ./main content header -->

<div class="container">
	<div class="about-us">
		<div class="row">
			<div class="col-md-12">
								
				
					<h2>Offer Received </h2>

								<p>
									<?php echo $this->first_name. ', thanks for requesting your offer. We will contact you within three working hours.'; ?>
								</p>								


				
					
	
					
					
			</div><!-- /.col-md-12 - main content -->
		</div><!-- /.row -->
	</div><!-- /.about-us -->
</div><!-- /.container -->
